### ISSUE TITLE
Properly serialize errors (cookies.set & some other API calls)

### ISSUE THREAD

**Issue by fluffywaffles** [segmentio/nightmare#1222] opened 2017-08-17 21:38 UTC
From what I can tell, `url` is **NOT** optional when your cookie has a `domain`, and it appears that it also must match. Just sunk an hour into this. Is Nightmare supposed to fill in `url` correctly when none is given but the cookie has a `domain`? The docs led me to believe it would just fill in `url` whenever it was missing. The error, when you don't have a matching `domain` and `url`, is super annoying and subtle, and manifests in a very obscure, propagating "{}" result.

Examples:
```
Nightmare()
  .goto('https://www.google.com')
  .cookies.set({ name: 'hi', value: 'there', domain: 'https://www.google.com' })
  .evaluate(function () { return document.title })
  .then(console.log.bind(console)) // => prints "{}"
```

```
Nightmare()
  .goto('https://www.google.com')
  .cookies.set({ name: 'hi', value: 'there', domain: 'https://www.google.com', url: 'https://somedomain.com/' })
  .refresh() // doesn't happen
  .cookies.get() // you can do whatever you want until the .then()
  .evaluate(function () { return document.title }) // it just won't work
  .then(console.log.bind(console)) // => prints "{}"
```

```
Nightmare()
  .goto('https://www.google.com')
  .cookies.set({ url: 'https://www.google.com', domain: 'https://www.google.com', name: 'hi', value: 'there' })
  .evaluate(function () { return document.title })
  .then(console.log.bind(console)) // => prints "Google", finally
```

```
Nightmare()
  .goto('https://www.google.com')
  .cookies.set({ url: 'https://www.google.com', domain: '.google.com', name: 'hi', value: 'there' })
  .evaluate(function () { return document.title })
  .then(console.log.bind(console)) // => prints "Google", too
```

**Comment by TimNZ** [comment] 2017-09-07 10:31
The Electron docs say it will be empty if not specified.
https://github.com/electron/electron/blob/master/docs/api/cookies.md#cookiessetdetails-callback

Not a Nightmare issue.

**Comment by fluffywaffles** [comment] 2017-09-07 18:57
The cookie field does default to empty. The problem isn't that; it's that this behavior contradicts documentation in the README, specifically: [If cookie.url is not set, it will set the cookie on the current url](https://github.com/segmentio/nightmare#cookiessetcookie).

If this was true, then the first example I provide, where `domain` is set but `url` is not, would succeed. Unless Nightmare is setting the url to something other than the one most recently loaded via `goto(...)`?

**Comment by TimNZ** [comment] 2017-09-07 19:52
Had a look at the Electron side code for cookie.set and it is definitely providing a URL if 'url' is not provided.

```
    parent.respondTo('cookie.set', function (cookies, done) {
        var pending = cookies.length

        for (var i = 0, cookie; cookie = cookies[i]; i++) {
            var details = Object.assign({
                url: webContents.getURL()
            }, cookie)

            parent.emit('log', 'setting cookie: ' + JSON.stringify(details))
            webContents.session.cookies.set(details, function (error) {
                if (error) done(error);
                else if (!--pending) done();
            })
        }
    })

```

Is it possible that the first example fails because you have a protocol (https://) in domain?  You should only have the hostname e.g. '.google.com' like you have on your last example.

Perhaps Electron/Chromium does some magic on cookie.set to do this for you if the hostname of url and domain are the same, and the url provided by Nightmare which it asks Electron for is different from the domain you specify.

Speculating, but I'm confident it's not a Nightmare issue as it passes along everything to Electron without modification aside from providing a 'url' value if not specified.

If you enable Nightmare logging you can see what it passes to Electron.

**Comment by matthewmueller** [comment] 2018-02-19 08:41
Dug into this one a bit. There's 2 problems:

@fluffywaffles, the 1st example doesn't actually work in electron. It will fail with: `Error: Setting cookie failed`

The bug in nightmare is that we're trying to serialize an error, leading to `{}`, which is less than helpful. You can see for yourself in the console with:

```js
JSON.stringify(new Error("oh noz"))
```

This problem is bigger than just `cookies.set`, we'll need to go through and make sure we're properly serializing all errors.

**Comment by matthewmueller** [comment] 2018-02-21 16:46
Closing since this is a duplicate of #646

**Closed by matthewmueller** 2018-02-21 16:46 UTC
Labels: 3.x, bug
