### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by thucnc** [segmentio/nightmare#225] opened 2015-09-16 17:38 UTC
Hello, I'm a newbie of nightmare, got this error: "Syntax error: unexpected identifier" for the below code
var nightmare = Nightmare();
function login () {
       var a = yield nightmare
	.goto('http://somewebpage.com')
}
Anyone can help.

**Comment by matthewmueller** [comment] 2015-09-16 20:54
Probably need `node --harmony index.js`

**Comment by thucnc** [comment] 2015-09-17 09:12
Thanks Matt, now I have a problem running nightmarejs on linux server (it does not do anything even throw exception/error). I guess I have the same problem as issue #228 . Please help

**Comment by reinpk** [comment] 2015-09-27 19:18
closing as a dupe of #228

**Closed by reinpk** 2015-09-27 19:18 UTC
