### ISSUE TITLE
electron-prebuilt error when deployed to Heroku

### ISSUE THREAD

**Issue by dylanvalade** [segmentio/nightmare#223] opened 2015-09-15 20:34 UTC
My app works locally using the CNN example.  However, after a Heroku build and deploy this error is logged when Nightmare is called.

``` sh
Error: spawn /tmp/build_aa182f5bde01ee44f4dcea91b391b552/node_modules/nightmare/node_modules/electron-prebuilt/dist/electron ENOENT
     at exports._errnoException (util.js:837:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
     at onErrorNT (internal/child_process.js:344:16)
     at doNTCallback2 (node.js:429:9)
     at process._tickCallback (node.js:343:17)
 events.js:141
      throw er; // Unhandled 'error' event
      ^

 Error: IPC channel is already disconnected
     at ChildProcess.target.disconnect (internal/child_process.js:630:26)
     at process.<anonymous> (/app/node_modules/nightmare/lib/nightmare.js:58:15)
     at emitOne (events.js:82:20)
     at process.emit (events.js:169:7)
     at process._fatalException (node.js:211:26)
```

package.json includes

``` js
"dependencies": {
    "ejs": "^2.0.0",
    "express": "^4.0.0",
    "nightmare": "^2.0.2",
    "vo": "^1.0.3"
  },
  "engines": {
    "node": "4.0.x"
  },
```

**Comment by reinpk** [comment] 2015-09-27 19:19
looks like the same issue as #224

**Comment by yoz** [comment] 2015-12-10 22:11
This is very different from #224 - this fails trying to start `electron-prebuilt`.

It looks like the `/tmp/build...` path comes from `electron-prebuilt` using `__dirname` in its install script, which has unexpected behavior on Heroku. This gets written into `path.txt` in `electron-prebuilt`. So I'm fairly sure it's a bug in `electron-prebuilt`.

**Comment by yoz** [comment] 2015-12-11 00:43
(Regretfully, after fixing this it does run into the same issue as #224 .)

**Comment by felixcrive** [comment] 2016-01-04 20:02
I am having the same issue on OS X (10.10.5) any ideas?

**Comment by yoz** [comment] 2016-01-04 20:33
@felixcrive the fix I referenced above should be fixed in electron 0.36.0 - does it work if you use the `electronPath` option with that newer electron?

**Comment by felixcrive** [comment] 2016-01-05 14:34
@yoz I doesn't work I have electron-prebuilt@0.36.2 and Nightmare@2.1.2 pointing to electronPath.

**Comment by rosshinkley** [comment] 2017-01-02 21:05
Given the age of this issue, I'm going to close it.  If you're still experiencing this issue, feel free to open a new issue.

**Closed by rosshinkley** 2017-01-02 21:05 UTC
