### ISSUE TITLE
Generic simulation of a mouse click in the page

### ISSUE THREAD

**Issue by maiopirata** [segmentio/nightmare#619] opened 2016-05-04 17:03 UTC
I have a slider in a page that can be clicked to choose the value.
This slider is really a div, styled with js to inject the right value in a React Component.
From the dom point of view everything is ruled with the left value of this div:
```
<div 
    class="handle handle-0 " 
    style="position: absolute; z-index: 1; left: 144px;" 
    data-reactid=".0.2.0.0.1.0.0.4.0.1.1.0.1.0.1:$handle0">
</div>
```
I would like to know if it is possible to simulate a mouse click in a position x,y with nightmare.
Any help is appreciated.

**Comment by rosshinkley** [comment] 2016-05-04 21:41
I suppose you could use `.evaluate()` and use [`document.elementFromPoint()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint).  An untested from-the-hip example:

```js
nightmare
  .goto(someUrl)
  .evaluate(function(x, y){
    document.elementFromPoint(x, y).click();
  }, x, y)
 //... other actions
```
... but that might not be granular enough for your application.  You could also initialize your own mouse event with a custom X,Y and issue it against the control at X,Y.  The [`MouseEvent`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent) docs may interest you.

If you wanted to get fancy, you could also write a plugin using Electron's [`webContents.sendInputEvent`](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentssendinputeventevent) to send `MouseDown` and `MouseUp` events.

**Comment by maiopirata** [comment] 2016-05-05 10:19
I used the evaluate function. Inside that I find the dom element that is basicaly a div rectangle listening for clicks.
I successfully have the element of the DOM.
```
var el = document.querySelector('#risk_profile > div');
var ev = new MouseEvent('click', {
        'view': window,
        'bubbles': true,
	'cancelable': true,
	'clientX': 100,
        'clientY': 1
});
el.dispatchEvent(ev);

```
I create than an offset element and I give an offset of 100.
Unfortunately the event is not dispatched correctly. What do you think I'm missing here?

Thanks

**Comment by rosshinkley** [comment] 2016-05-05 14:11
According to the [`MouseEvent` constructor docs](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent), at least in my naive read, `clientX`/`clientY` is relative to the client window, not to the DOM element (like it is for the readonly `clientX`/`clientY` on a caught `MouseEvent`).  What happens if you specify an absolute point?

**Comment by rosshinkley** [comment] 2016-05-05 14:29
Scratch that, I'm wrong, [jsbin](http://jsbin.com/coxekatofe/1/edit?html,js,console,output) to prove it.

Based on that little experiment, what you have ought to work.  Out of curiosity, what happens if you instead issue a `mouseDown`?

**Comment by maiopirata** [comment] 2016-05-05 16:47
I have tried the following.
First I find the correct position of the slider in absolute coordinates. Then I try to click it via the function.
It doesn't work via the browser console, nor via electron browser...
```
.evaluate(function(){
	var el = document.querySelector('#risk_profile > div');
	var xPos = 0;
	var yPos = 0;
	while (el) {
		if (el.tagName == "BODY") {
			// deal with browser quirks with body/window/document and page scroll
			var xScroll = el.scrollLeft || document.documentElement.scrollLeft;
		        var yScroll = el.scrollTop || document.documentElement.scrollTop;
			xPos += (el.offsetLeft - xScroll + el.clientLeft);
			yPos += (el.offsetTop - yScroll + el.clientTop);
		} else {
			// for all other non-BODY elements
			xPos += (el.offsetLeft - el.scrollLeft + el.clientLeft);
			yPos += (el.offsetTop - el.scrollTop + el.clientTop);
		}
		el = el.offsetParent;
    	}
	el = document.querySelector('#risk_profile > div');
	// now you have the right left,top global position!
	var ev = new MouseEvent('click', {
        	'view': window,
		'bubbles': true,
		'cancelable': true,
		'screenX': xPos + 50,
		'screenY': yPos
	});
	el.dispatchEvent(ev);
	return true;
})
```

**Comment by Mr0grog** [comment] 2016-05-06 18:54
@maiopirata your code above seems perfectly correct. What are you expecting to have happen? Do you have a `click` event listener on the `div` or on an element that contains it? When you dispatch a simulated event this way, an element *inside* the div at the given position *will not receive the event.* This will also not automatically trigger the relevant `mousedown` and `mouseup` events, so if you are actually listening for those, your listeners will not be triggered.

It is also worth noting that none of the default behaviors that a browser does will be triggered when you dispatch events this way (that’s why you might want to use `webContents.sendInputEvent` as @rosshinkley mentioned—that *will* cause default browser behaviors).

Side note: you can actually get the position of the element relative to the viewport much more easily than you are doing above:

```js
var el = document.querySelector('#risk_profile > div’);
var bounds = el.getBoundingClientRect();
var xPos = bounds.left;
var yPos = bounds.top;
```

**Comment by maiopirata** [comment] 2016-05-06 21:41
Thank you @Mr0grog for your answer. I will definitely test webContents, it seems that this is the point.
Thank you also that you show me bounds.left, top.. It would have saved me a lot of time knowing it some days before.

I will let you know soon

**Comment by dsowsy** [comment] 2016-05-10 18:42
I'm trying to do similar as well. I want to write automation tests for canvas drawing and need to do mousemove/mousedown/mouseup at a specific coordinate (x,y).

Is there any reason _not_ to attempt to expose a method like sendEvent that PhantomJS has? 
http://phantomjs.org/api/webpage/method/send-event.html

For this specific use case, I was able to get sendEvent working with PhantomJS events, but would prefer Nightmare because it's just a lot nicer/cleaner overall. Initially I just assumed it was an Electron bug/ swallowed event, but figured I'd ask first if it was working as intended. 

@rosshinkley I'm not sure this is fancy, but I'm not sure how to make the driver yet either. :)

**Comment by Mr0grog** [comment] 2016-05-10 21:47
@rosshinkley do you have any idea why the `click()` (and `mouseover/mousedown`) action doesn’t use `sendInputEvent`? Assuming no, since according to git, they pretty much appeared out of whole cloth, but asking just in case.

Seems like upgrading them to use `sendInputEvent` would be more “correct,” though it would change behavior slightly.

**Comment by Mr0grog** [comment] 2016-05-18 06:08
If it helps anyone here, I wrote a little example plugin for how to use `sendEvent` over on #639. @dsowsy for your case, just throw some `mousemove` events in between the `mousedown` and `mouseup`:

```js
win.webContents.sendInputEvent({ type: 'mousemove', x: x, y: y });
```

It would be good to get a sense if this approach actually works for people like you before spending the effort cleaning it up for adding to core.

**Comment by rosshinkley** [comment] 2016-05-18 16:47
> @rosshinkley do you have any idea why the click() (and mouseover/mousedown) action doesn’t use sendInputEvent? Assuming no, since according to git, they pretty much appeared out of whole cloth, but asking just in case.

I _suspect_ it's because `sendInputEvent` wasn't a part of the Electron API when 2.x was initially released.  (The release dates differ by something like 10 days, memory serving.)  I also suspect that it worked Good Enough&trade;, so before now there hasn't been a real reason to change it.

> Seems like upgrading them to use sendInputEvent would be more “correct,” though it would change behavior slightly. (Maybe a good v3 change?)

I'd like to (like you) see more usage before making the change, but I also agree this feels much more in the spirit of "doing things as an actual user would", which is in keeping with the spirit of Nightmare.  Given that it seems to be causing enough problems, I'd be open to moving it into core.  Thoughts?

**Comment by Mr0grog** [comment] 2016-05-19 01:15
> Given that it seems to be causing enough problems, I'd be open to moving it into core. Thoughts?

Well, it sounds like there are either some bugs with it or it is not solving the problem: https://github.com/segmentio/nightmare/issues/639#issuecomment-219953581 It needs feedback from @timotgl or I or someone should do some testing w/ React. I wouldn’t want to change this part of core if it doesn’t actually solve the issues people are encountering.

It also might be worth postponing to v3—it won’t work on elements that aren’t being displayed (the current implementation does) and it will work differently than the current implementation on elements with children or that are obscured/overlapped by other elements (the events will go to the element at the click location, not necessarily to the element identified by the selector). Most of the time this should be a non-issue, but it’ll almost certainly bite someone.

**Comment by Mr0grog** [comment] 2016-05-20 23:51
Basic plugin that people can use here: https://github.com/Mr0grog/nightmare-real-mouse
Or just `npm install nightmare-real-mouse`

Maybe that can sit for a while and see if it solves issues for people?

**Comment by maiopirata** [comment] 2016-05-25 16:54
Sorry for the late answer. What you did looks great. I'll let you know as soon as I put my hands on it again...

**Comment by rosshinkley** [comment] 2016-07-09 17:21
Closing for lack of activity (and looks like this is possibly resolved).  If this is still an issue, feel free to reopen/submit a new issue.

**Closed by rosshinkley** 2016-07-09 17:21 UTC

**Comment by wojtekmaj** [comment] 2018-08-22 09:02
If you look for a quick solution to extend Nightmare with actions like `.middleClick`, `.ctrlClick()` etc., I just released [nightmare-advanced-click](/wojtekmaj/nightmare-advanced-click) :)
