### ISSUE TITLE
electron crash during testing - any ways to mitigate/catch such errors?

### ISSUE THREAD

**Issue by AVVS** [segmentio/nightmare#545] opened 2016-03-28 09:57 UTC
I'm trying to automate testing paypal integrations and after another annoying update on the paypal side electron starts crashing at the last action, code that I'm posting had worked before (like 4 weeks ago), but then started resulting in a crash. Hopefully some1 can hint me on how to fix/avoid it - I would really appreciate it.

Here are the logs and the code:

https://gist.github.com/AVVS/f641c1535cde2a258e71

``` js
function approve(saleUrl) {
    const browser = new Nightmare({
      waitTimeout: 15000,
    });

    return new Promise(_resolve => {
      const resolve = once(_resolve);

      const _debug = require('debug')('nightmare');

      function parseURL(newUrl) {
        if (newUrl.indexOf('redirect-url') >= 0) {
          const parsed = url.parse(newUrl, true);
          resolve({ token: parsed.query.token, payer_id: parsed.query.PayerID, payment_id: parsed.query.paymentId });
        }
      }

      browser
        .on('did-get-redirect-request', (events, oldUrl, newUrl) => {
          _debug('redirect to %s', newUrl);
          parseURL(newUrl);
        })
        .on('did-get-response-details', (event, status, newUrl) => {
          _debug('response from %s', newUrl);
          parseURL(newUrl);
        })
        .on('will-navigate', (event, newUrl) => {
          _debug('navigate to %s', newUrl);
          parseURL(newUrl);
        })
        .goto(saleUrl)
        .screenshot('./ss/pre-email.png')
        .wait('#loadLogin')
        .click('#loadLogin')
        .wait('#login_email')
        .type('#login_email', false)
        .wait(3000)
        .type('#login_email', 'test@cappacity.com')
        .type('#login_password', '12345678')
        .wait(3000)
        .screenshot('./ss/after-email.png')
        .click('#submitLogin')
        .screenshot('./ss/right-after-submit.png')
        .wait(3000)
        .screenshot('./ss/after-submit.png')
        .wait('#continue')
        .screenshot('./ss/pre-confirm.png')
        .click('#continue')
        .screenshot('./ss/right-after-confirm.png')
        .wait(3000)
        .screenshot('./ss/after-confirm.png')
        .end()
        .then(() => {
          console.log('completed running %s', saleUrl);
          resolve();
        });
    });
  }
```

**Comment by Mr0grog** [comment] 2016-04-12 18:16
First off, are you on the latest release of Nightmare? There have been some changes to screenshotting lately, which is the thing Nightmare does that is most likely to trigger crashers in Electron. The first thing I might try if you are on the latest Nightmare is to remove all your screenshot calls and see if it still crashes.

Regardless, this sounds like a problem in Electron. Are you using the latest version of electron? If you have Nightmare installed globally, you can check by calling:

```sh
electron --version
```

Or if installed locally:

```sh
./node_modules/.bin/electron --version
```

The latest that nightmare will install is 0.36.12 and the latest possible is 0.37.5. To update, you could blow away the directory for `electron-prebuilt` that is in either `node_modules` or `node_modules/nightmare` and then `npm install electron-prebuilt`.

If you’re up-to-date and still crashing, you ought to be able to grab a crash report from somewhere on your system. I’m not sure where to get it on other OSes, but in OS X, you can most easily get it from the Console app in Applications -> Utilities -> Console. You’ll see a line like:

`4/12/16 10:54:50.155 AM ReportCrash[32556]: Saved crash report for Electron[32596] version 0.37.5 (0.37.5) to /Users/rbrackett/Library/Logs/DiagnosticReports/Electron_2016-04-12-105450_Lilpix.crash`

With a little arrow to the left. Click the arrow, then the “Open Report” button that appears to get the crash report. It might help us here, but most likely you’ll just want to submit it to the Electron team over at https://github.com/electron/electron/issues

**Comment by bahlo** [comment] 2016-04-22 13:02
I have the latest electron-prebuilt and get exactly the same error (see #587).

Any other ideas?

**Comment by rosshinkley** [comment] 2016-04-23 22:51
Not sure that it matters, but you might want to also override [the Electron path](https://github.com/segmentio/nightmare#electronpath).  I don't _think_ the paths changed from 0.36.x to 0.37.x, so @Mr0grog's directions should work, but it can't hurt to be sure.  You may also want to run your application with `ELECTRON_ENABLE_LOGGING` in tandem with `DEBUG=nightmare:*,electron:*`.  That might give you a little more information.

What bothers me about the original log text is that the error is a page error from `.onClick()`, so I'm not certain it's because of the screenshot.  If I had to guess, I'd guess that there's a problem in PayPal's client code when you click on `#loadLogin`.  If you run the steps by hand in Chrome with the devtools open, do you get the same error?

**Comment by Mr0grog** [comment] 2016-04-25 19:55
Regardless, since it’s a crash in Electron, getting the crash report would help a lot. It’s extremely hard to know what’s causing the crash without either a reproducible test case or knowledge of what Electron is actually doing when it crashes (from the crash report).

If you can’t get the crash report from the system, you can also try setting `ELECTRON_ENABLE_STACK_DUMPING` (not just `ELECTRON_ENABLE_LOGGING`) alongside `DEBUG=electron:*` as @rosshinkley suggested. That’ll at least get you something similar to the system report.

**Comment by rosshinkley** [comment] 2016-04-25 20:09
@Mr0grog This is about a thousand miles offtopic, but would it be worth implementing a crash report server internal to Nightmare so the child Electron instance submits crash reports directly to the parent process?

**Comment by Mr0grog** [comment] 2016-04-25 20:15
> would it be worth implementing a crash report server internal to Nightmare

Yeah, that would probably be pretty neat to have.

**Comment by rosshinkley** [comment] 2016-04-25 20:16
> Yeah, that would probably be pretty neat to have.

I'll open up a new issue for that so we don't pollute this thread. :)

Throwing it on the todo pile...

**Comment by rosshinkley** [comment] 2017-01-02 21:21
With #598 being done and the recent changes to the screenshot API, I'm going to close this issue.  Feel free to open a new issue if this is still a problem.

**Closed by rosshinkley** 2017-01-02 21:21 UTC
