### ISSUE TITLE
does anyone get "ERR_NO_SUPPORTED_PROXIES" when use proxy in nightmare?

### ISSUE THREAD

**Issue by codenessjl** [segmentio/nightmare#1345] opened 2017-12-15 08:53 UTC
As the title,very grateful!

**Comment by mck457** [comment] 2018-01-06 19:10
same issue

**Comment by matthewmueller** [comment] 2018-02-13 09:06
duplicate of #1354. Please provide an example of your code to help with debugging

**Closed by matthewmueller** 2018-02-13 09:06 UTC
