### ISSUE TITLE
Race condition in evaluate

### ISSUE THREAD

**Issue by LinusU** [segmentio/nightmare#693] opened 2016-06-21 14:22 UTC
It seems like evaluate can sometimes hang and never resolve the promise if the page is navigating at the same time that the evaluation is happening.

In our application we are constantly running a polling function that will check in what state we are in, on a page that is reloading from time to time to show new data. The code looks something like this:

``` js
const waitForState = co.wrap(function * (browser) {
  for (let tries = 720; tries > 0; tries--) {
    debug('Queing read of state')
    const state = yield browser.evalutate(readState)
    debug(`Got state "${state}")

    // (yield sleep or return value)
  }

  // (throw timeout)
})
```

In some cases the function simply hangs, this is an example of the output:

``` text
linusu:test Queueing read of state +256ms
nightmare:actions .evaluate() fn on the page +0ms
linusu:test Got state "null" +18ms
linusu:test Queueing read of state +256ms
nightmare:actions .evaluate() fn on the page +0ms
linusu:test Got state "null" +18ms
linusu:test Queueing read of state +256ms
nightmare:actions .evaluate() fn on the page +0ms
linusu:test Got state "null" +18ms
nightmare:log did-get-response-details +210ms ...
nightmare:log did-start-loading +16ms ...
linusu:test Queueing read of state +24ms
nightmare:actions .evaluate() fn on the page +5ms
linusu:test Got state "null" +2ms
nightmare:log did-get-redirect-request +44ms ...
nightmare:log will-navigate +0ms ...
nightmare:log did-fail-provisional-load +5ms ...
nightmare:log did-fail-load +0ms ...
nightmare:log page-favicon-updated +0ms ...
nightmare:log did-get-response-details +111ms ...
linusu:test Queueing read of state +90ms
nightmare:actions .evaluate() fn on the page +1ms
nightmare:log did-get-response-details +21ms ...
nightmare:log did-get-response-details +1ms ...
nightmare:log did-get-response-details +4ms ...
nightmare:log did-get-response-details +0ms ...
nightmare:log did-get-response-details +2ms ...
nightmare:log did-get-response-details +0ms ...
nightmare:log did-get-response-details +1ms ...
nightmare:log did-get-response-details +0ms ...
nightmare:log did-get-response-details +26ms ...
nightmare:log did-get-response-details +41ms ...
nightmare:log did-get-response-details +1ms ...
nightmare:log did-get-response-details +1ms ...
nightmare:log did-get-response-details +1ms ...
nightmare:log did-get-response-details +19ms ...
nightmare:log did-get-response-details +25ms ...
nightmare:log dom-ready +0ms ...
nightmare:log did-get-response-details +0ms ...
nightmare:log did-frame-finish-load +12ms ...
nightmare:log did-finish-load +0ms ...
nightmare:log did-get-response-details +347ms ...
nightmare:log did-get-response-details +109ms ...
nightmare:log did-get-response-details +0ms ...
nightmare:log did-get-response-details +3ms ...
nightmare:log did-get-response-details +0ms ...
nightmare:log did-get-response-details +7ms ...
nightmare:log dom-ready +6ms ...
nightmare:log did-get-response-details +30ms ...
nightmare:log did-get-response-details +0ms ...
nightmare:log did-get-response-details +2ms ...
nightmare:log did-get-response-details +4ms ...
nightmare:log did-get-response-details +2ms ...
nightmare:log did-get-response-details +0ms ...
nightmare:log did-frame-finish-load +0ms ...
nightmare:log did-finish-load +0ms ...
nightmare:log page-favicon-updated +1ms ...
nightmare:log did-stop-loading +0ms ...
```

It's a bit spammy, sorry about that, but as you can see it prints my first debug statement (`linusu:test Queueing read of login status +90ms`) and then nightmare runs the action (`nightmare:actions .evaluate() fn on the page +1ms`), but then it never returns to me so that my second debug statement can run.

I'd be happy to provide any more information that might be relevant, and I'll try to put together a test case.

**Comment by rosshinkley** [comment] 2016-06-25 23:45
Hm, out of curiosity, what version of Nightmare are you using?

I thought that if the page was loading, Nightmare would wait for the artificial `did-change-is-ready` event before continuing from a `did-stop-loading` event.  In other words, a race condition while loading shouldn't be possible because the action chain _should_ be blocked.

I'd love to see a minimum case if you could throw one together.  As time permits, I'll see if I can reproduce the problem.

**Comment by rosshinkley** [comment] 2016-08-08 16:55
@LinusU Bumping this thread - did you either get this resolved or put together a repro?

**Comment by LinusU** [comment] 2016-08-09 08:37
Sorry for the radio silence, I never managed to solve it but I worked around it by not running evaluate in a loop :)

I have still to put together a test case, time has been tight as always...

**Comment by rlidwka** [comment] 2016-09-27 18:25
I just resolved race condition in `navit`. Assuming that the electron wrapper is written the same way, I decided to write here in case you're having the similar issue.

The problem was: during initial page load, `webContents.executeJavaScript` never actually executes (it never returns a callback if you're using `executeJavaScript(code, callback)` interface, the same I imagine is true for events).

So you'd need to wait until the page actually loads. I suggest checking `webContents.isWaitingForResponse` and if it's true, delay javascript evaluation until `did-stop-loading` event.

Something like this should work (I'm not entirely sure, so please test it out):

```diff
--- a/lib/runner.js
+++ b/lib/runner.js
@@ -335,7 +335,14 @@ app.on('ready', function() {
     renderer.once('error', error);
     renderer.on('log', log);
 
-    win.webContents.executeJavaScript(src);
+    if (win.webContents.isWaitingForResponse()) {
+      win.webContents.once('did-stop-loading', () => {
+        // isWaitingForResponse() flips to false at this point
+        win.webContents.executeJavaScript(src);
+      });
+    } else {
+      win.webContents.executeJavaScript(src);
+    }
   });
 
   /**
```

Here is a the commit in `navit`, so you can try to salvage tests and such: https://github.com/nodeca/navit/commit/6525dc7bf414894324d2ca8e99f076c24781f06f

**Comment by barczaG** [comment] 2016-10-25 16:56
+1 . 
Evaluate sometimes files if page is navigating.
Workaround was to ensure somehow that page is not navigating (eg. wait on some fix selector)

**Comment by nfarina** [comment] 2017-02-15 23:11
Experiencing this mostly on production (free/slow Heroku dyno). This definitely feels like a race condition.

My workaround was to wrap every `evaluate` call (or function like `wait` which can use evaluate internally) and perform `nightmare.wait('html')` before attempting the _real_ wait/evaluate call.

**Comment by casesandberg** [comment] 2017-08-22 19:05
Go ahead and try out the headless Chrome implementation in v3, it fixes this exact issue! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if it's still an issue.

**Closed by casesandberg** 2017-08-22 19:05 UTC
