### ISSUE TITLE
How to set viewport after evaluating body dimensions?

### ISSUE THREAD

**Issue by moroshko** [segmentio/nightmare#498] opened 2016-02-23 11:36 UTC
First of all, thanks for the great library!

In order to take a whole page screenshot, I'm trying to set the viewport after evaluating `body`'s width and height. But, I'm not sure how to use the evaluated `width` and `height` when calling `.viewport()`:
```js
Nightmare()
  .goto(url)
  .wait(selector)
  .evaluate(() => {
    const body = document.querySelector('body');

    return {
      height: body.scrollHeight,
      width: body.scrollWidth
    };
  })
  // How do I use the returned `width` and `height` to set viewport now?
```
I found [this example](https://github.com/segmentio/nightmare/issues/328#issuecomment-159311982), but it uses generators. I wonder if it's possible to achieve the same without generators?

**Comment by rosshinkley** [comment] 2016-02-23 15:55
Yes.  As of v2.2.0, `.then()` returns a native `Promise`.  That original example from #328, rewritten without generators, using only promises:

```javascript
var nightmare = Nightmare();
nightmare
  .goto(url)
  .wait(selector)
  .evaluate(() => {
    const body = document.querySelector('body');

    return {
      height: body.scrollHeight,
      width: body.scrollWidth
    };
  })
  .then(function(dimensions) {
    return nightmare
      .viewport(dimensions.width, dimensions.height)
      .wait(1000)
      .screenshot(require('path').join(__dirname, 'screenshot.png'))
  })
  .then(function() {
    nightmare.end(function() {
      console.log('done');
    });
  });
```

You could use your favorite native promise-supporting library to do flow control as well.

**Comment by moroshko** [comment] 2016-02-24 05:10
@rosshinkley Thanks a lot for this! 
Just wondering, why `.wait(1000)` is required before taking the screenshot?

**Comment by rosshinkley** [comment] 2016-02-24 05:22
No problem!

With respect to the call to `.wait()`, that is a _great_ question.  It has to do with allowing Electron's internal backing frame storage to catch up to the current rendering of the page.  If you don't allow this to take place, the image will be of the previous viewport dimensions distorted to the new dimensions.

You might want to take a look at #468 which outlines the issue and #479 which addresses the problem.

**Comment by moroshko** [comment] 2016-02-25 11:37
@rosshinkley Ah! So, once #479 is merged, we'll no longer need the `.wait(1000)`?

**Comment by mousemke** [comment] 2016-02-25 12:23
I'm going to dump this here due to no(obvious) better place (does nightmare have a irc/slack/gitter/etc?).

Using this method, the screenshot dimensions are exactly double the dimensions I set.  Am I missing something?

**Comment by rosshinkley** [comment] 2016-02-25 19:53
@moroshko That's right.  Once #479 is fixed, no more "magic" wait calls.

@mousemke #272 was opened to petition for a gitter room, you might want to go give that some support. :)

Addressing your question: that's curious.  Is that the case for _any_ screenshot, or only screenshots taken with getting the body dimensions first?

**Comment by mousemke** [comment] 2016-02-26 08:11
screen shots appear to always be double sized. in this case either 2048x1600 or double the supplied dimentions

```javascript
/**
 * ## promiseScreenshot
 *
 * gets a screenshot of the supplied element
 *
 * @param {String} tag selector
 *
 * @return _Promise_ the nightmare must end eventually
 */
var promiseScreenshot = function( tag )
{
    return new Promise( function( resolve, reject )
    {
        var tagSafe = tag.split( ',' )[0];
        var nightmare = new Nightmare();

        nightmare.viewport( 1024, 768 )
            .goto( url )
            .wait()
            // i wont bother linking getBoundingRectangle, but it
            // just gets the dimentions
            .evaluate( getBoundingRectangle, tag )
            .then( rect =>
            {
                // console output to double check i'm getting the right values
                console.log( rect );
                if ( rect )
                {
                    var path = screenshotDir + '/' + tagSafe + '.png';

                    return nightmare.scrollTo( rect.y, rect.x )
                        // tested without the resize
                        .viewport( rect.width, rect.height )
                        .wait( 1000 )
                        // tested without the rect restraints.  
                        // it takes 2048x1600 screenshots
                        .screenshot( path, rect );
                }
            } )
            .then( () => resolve( nightmare.end() ) );
    } );
};
```

**Comment by mousemke** [comment] 2016-02-26 08:13
btw: this was node version `5.0.0`  I now updated to `5.7.0` and it is the same

**Comment by rosshinkley** [comment] 2016-03-05 04:56
Hm, I still can't reproduce this behavior.

Even if you start a fresh project with a fresh install of Nightmare, doing a simple shot produces this result?  Something like:

```js
var Nightmare= require('nightmare'),
  nightmare = Nightmare({show:true});

nightmare.goto('http://example.org')
  .viewport(150,150)
  .wait(1000)
  .screenshot('shot.png')
  .end()
  .then(function(){
    console.log('done');
  });
```

**Comment by rosshinkley** [comment] 2016-04-03 03:51
@mousemke Are you still having this issue?

**Comment by mousemke** [comment] 2016-04-03 12:31
Yes, but I've just learned to deal with it. Havn't looked into fixes in a while

**Comment by Mr0grog** [comment] 2016-04-16 01:56
@mousemke sorry if this is obvious and you already thought of it, but are you on a device with a retina or other high-res display, like a Chromebook pixel, Retina MacBook Pro, etc? Electron will definitely give you a screenshot with “double the pixels” (or something else if you have a more than 2x display). The viewport dimensions you set are in “effective pixels” or “CSS pixels,” not device pixels.

I’m not sure there’s any way to explicitly change that, but writing a plugin will give you access to all the relevant modules in Electron: `screen` will tell you the scale factor for each display; `WebFrame` will let you do zooming, which you could use then use to counteract the scale factor—set the viewport to half your desired size and zoom to 0.5 to get 1:1 pixels, for example.

**Comment by pci** [comment] 2016-04-19 15:44
Able to reproduce on a high-dpi device: the screenshot is 2x the height/width set in nightmare. @Mr0grog's  reasoning about the source seems valid.

**Comment by rosshinkley** [comment] 2016-04-23 20:31
@Mr0grog @pci Of course! High device resolution!  That makes sense.

With that last mystery solved, I'm closing this issue as I think it has been fully resolved.

**Closed by rosshinkley** 2016-04-23 20:31 UTC

**Comment by dtipson** [comment] 2016-07-14 01:44
The retina thing should probably go in the readme.  Just threw me when I tried it, and it totally makes sense! But should note that it ss's to dpi rather than strictly 1x1 pixels.

**Comment by sebastienbarre** [comment] 2016-12-09 05:17
@Mr0grog  I'm struggling on this one, how do you access WebFrame to do the zooming, from `evaluate()` ? I get a `webFrame is not defined`. Thx

**Comment by Mr0grog** [comment] 2016-12-09 07:08
`WebFrame` and `screen` are Electron APIs, so you either need to get them by writing a plugin using [the `action` method](https://github.com/segmentio/nightmare#nightmareactionname-electronactionelectronnamespace-actionnamespace) or by using a [custom preload script](https://github.com/segmentio/nightmare#custom-preload-script).

If you just *always* want rendering at a particular resolution, you can also use the Chromium command line `force-device-scale-factor` switch. Here’s an example: https://github.com/segmentio/nightmare/blob/master/test/index.js#L1830 You can't change that after you start Nightmare, though.

**Comment by sebastienbarre** [comment] 2016-12-09 14:25
@Mr0grog `force-device-scale-factor` did the trick -- many thanks.

**Comment by sebastienbarre** [comment] 2016-12-09 20:57
Funny thing, my screenshots are now distorted too.
Capturing a simple screenshot worked. But capturing a rectangle produces a screenshot distorted vertically.

```
        var rect = yield nightmare
          .goto(url)
          .wait(screenshotSelector)
          .evaluate(function(selector) {
            var element = document.querySelector(selector)
            if (element) {
              var rect = element.getBoundingClientRect()
              return {
                x: Math.round(rect.left),
                y: Math.round(rect.top),
                width: Math.round(rect.width),
                height: Math.round(rect.height)
              }
            }
            return false
          }, screenshotSelector)

        if (rect !== false) {
          yield nightmare
            .screenshot(filename, rect)
        }
```
I'm not touching the viewport in this scenario. Should I make the viewport infinitely high?

**Comment by sebastienbarre** [comment] 2016-12-09 23:21
I take that back, I can't set the viewport to the the `body` dimensions, because it completely messes pages that use CSS `background-image` in cover mode.

Would you guys know why getBoundingClientRect would return "distorted" coordinates? Do I need to convert them to some physical pixel units through a multiplier? It doesn't look related to the device pixel ratio I'm on.

**Comment by hhrogersii** [comment] 2017-11-15 22:10
In case this might help anyone running into an aspect ratio problem, I was struggling with a vertical increase in aspect ratio with:
```
    let nightmare = Nightmare({
            show: false,
            width: format.width,
            height: format.height,
        });

    nightmare
        .goto(fixture)
        .evaluate((request) => {
            var s = document.styleSheets[0];
            s.insertRule('::-webkit-scrollbar { display:none; }');
            reset();
            render(request);
        }, request)
        .viewport(format.width, format.height)
        .wait(1000)
        .screenshot({
            x: 0,
            y: 0,
            width: format.width,
            height: format.height,
        })
```
After adding ``frame: false`` to the Nightmare instantiation my problems went away.
