### ISSUE TITLE
"Uncaught Exception" while running "nightmare" in a loop

### ISSUE THREAD

**Issue by rahul-desai3** [segmentio/nightmare#289] opened 2015-10-15 21:57 UTC
I am trying to crawl a domain completely and ignoring the external domain links. I have written a `while` loop for that, but it ran into an exception.

Here is my code so far:

```
var Nightmare = require('nightmare');
var vo = require('vo');

var link = 'https://www.cordbloodbanking.com/';

vo(run)(function(err, result) {
	if (err) throw err;
});


function *run() {

	var seen = ignored = linksQueue = [];

	linksQueue.push(link);

	while(linksQueue.length > 0){

		var nightmare = Nightmare();

		var link = linksQueue.pop();

		var n = yield nightmare
			.goto(link)
			.evaluate(function() {

				console.log('evaluating..');  // never works

				var links = document.querySelectorAll("a");

				for(var i = 0, l = links.length; i < l; i++){
	    			if(!seen[links[i].href] && !ignored[links[i].href]){
	    				if(/^https:\/\/www\.cordbloodbanking\.com/.test(links[i].href) || /^\//.test(links[i].href)){
	    					linksQueue.push(links[i].href);
	    					seen[links[i].href] = true;
	    				} else {
	    					ignored[links[i].href] = true;
	    				}
	    			}
				}
			});
	};

	console.log('CRAWLING COMPLETE!');
	console.log('Links visited:', seen);


	yield nightmare.end();
}
```
Here is how I ran it:
```
Rahuls-MacBook-Air:nightmare rahuldesai$ DEBUG=nightmare node --harmony index.js 
  nightmare queueing action "goto" for undefined +0ms
  nightmare queueing action "evaluate" +4ms
```
Here is what I got as soon as I ran it:

![screen shot 2015-10-15 at 5 49 18 pm](https://cloud.githubusercontent.com/assets/2539881/10528690/b86b0436-7365-11e5-9fe5-9485374c74e8.png)

How do I fix this?

**Comment by LarryBattle** [comment] 2015-10-18 23:01
This is your problem.

    nightmare queueing action "goto" for undefined +0ms

You're passing in a undefined link because the global `link` is overwritten in the context of `run()`.
There are two ways you can fix this.
1. Rename the global `link` variable to something else, like `bacon`
2. Change `var link = linksQueue.pop();` to `link = linksQueue.pop();`

**Comment by rahul-desai3** [comment] 2015-10-18 23:16
@LarryBattle That was my bad. I tried both of your solutions and it gives me `undefined`.

```
rahul@rahul-Inspiron-N5010:~/stuff$ DEBUG=nightmare node --harmony nig.js 
  nightmare queueing action "goto" for https://www.cordbloodbanking.com/ +0ms
  nightmare queueing action "evaluate" +7ms
undefined
rahul@rahul-Inspiron-N5010:~/stuff$ 
```

I am not sure why exactly it is breaking.

**Comment by LarryBattle** [comment] 2015-10-18 23:58
Oh. It's because `.evaluate()` executes the function you passed in the context on the browser, which doesn't have access to your link variables unless you pass them directly to `.evalulate()` as additional arguments. 
I hope this example makes this.

	var moduleFnArg1 = 1
	var moduleFnArg2 = 2
	var moduleFn = function(arg1, arg2){
		console.log( "Got arg1 as %s, and arg2 as %s", arg1, arg2)
	}
	yield nightmare
	.goto(link)
	.evalulate(moduleFn, moduleFnArg1, moduleFnArg2)

**Comment by rahul-desai3** [comment] 2015-10-19 00:11
@LarryBattle I tried your example but it gave me `undefined` in the console. Here is my code: https://gist.github.com/rahul-desai3/8ee6f5322e17a34116ba

**Comment by LarryBattle** [comment] 2015-10-19 07:29
You're getting `undefined` because `* run()` is called by `vo()` before the other global variables are initialized. This causes `* run()` to stores references to `undefined` values. Place the `vo()` part at the end of the script and run it again.

Here's a simple and short working example of extracting the links on a page.

	var Nightmare = require('nightmare');
	var vo = require('vo');

	var homeUrl = 'http://www.wimp.com/'

	var findUnseenRelativeLinks = function(baseUrl, viewedLinks) {
	    var markedLinks = {}
	    var links = document.querySelectorAll("a");

	    for (var i = 0; i < links.length; i++) {
		var href = links[i].href;
		if (!markedLinks[href] && !viewedLinks[href] && (/^\//.test(href) || href.indexOf(baseUrl) != -1)) {
		    markedLinks[href] = 1;
		}
	    }
	    
	    return Object.keys(markedLinks).sort();
	}

	function* findNewLinksToVisitFromLink(viewedLinks, url, nightmare) {
	    var links = yield nightmare.goto(url).evaluate(findUnseenRelativeLinks, homeUrl, viewedLinks)
	    return links;
	}

	function * run() {
	    var nightmare = Nightmare();
	    var viewedLinks = {};
	    var linksToVisit = [homeUrl];

	    // @TODO Refactor this section to view to a breath first search on the new links
	    var url = linksToVisit.pop() 
	    viewedLinks[url] = 1;
	    var links = yield * findNewLinksToVisitFromLink(viewedLinks, url, nightmare);
	    // end of breath first search

	    console.log(links);
	    yield nightmare.end();
	}

	vo(run)(function(err, result) {
	    if (err) throw err;
	});

**Comment by rahul-desai3** [comment] 2015-10-19 18:06
@LarryBattle That works very well on my local. However, when I put this on Heroku, it doesnt. Here is what I get:

```
2015-10-19T17:58:22.372868+00:00 app[web.1]: Mon, 19 Oct 2015 17:58:22 GMT nightmare queueing action "evaluate"
2015-10-19T17:58:22.368523+00:00 app[web.1]: Mon, 19 Oct 2015 17:58:22 GMT nightmare queueing action "goto" for https://github.com
2015-10-19T17:58:22.377707+00:00 app[web.1]: Error: spawn /tmp/build_19b8229474da1b68ec2af6357882e756/node_modules/nightmare/node_modules/electron-prebuilt/dist/electron ENOENT
2015-10-19T17:58:22.377710+00:00 app[web.1]:     at exports._errnoException (util.js:837:11)
2015-10-19T17:58:22.377712+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
2015-10-19T17:58:22.377713+00:00 app[web.1]:     at onErrorNT (internal/child_process.js:344:16)
2015-10-19T17:58:22.377714+00:00 app[web.1]:     at doNTCallback2 (node.js:429:9)
2015-10-19T17:58:22.377714+00:00 app[web.1]:     at process._tickCallback (node.js:343:17)
2015-10-19T17:58:52.246164+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/getLinksAndEmails" host=email-finder.herokuapp.com request_id=fc837338-24d7-4f86-b3f8-5bfd129f3b94 fwd="71.42.53.69" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0
```

**Comment by LarryBattle** [comment] 2015-10-20 06:17
Related issue: https://github.com/segmentio/nightmare/issues/224

**Comment by reinpk** [comment] 2015-10-25 19:44
thanks! gonna close as a duplicate of #224 as @LarryBattle mentioned

**Closed by reinpk** 2015-10-25 19:44 UTC
Labels: question
