### ISSUE TITLE
Running inside X Virtual Frame Buffer

### ISSUE THREAD

**Issue by sriducati** [segmentio/nightmare#411] opened 2015-12-24 12:30 UTC
Nightmare works fine when we start with...

    xvfb-run node cnn.js

assuming cnn.js has....

		var Nightmare = require('../nightmare');
		var vo = require('vo');

		vo(run)(function(err, result) {
		  if (err) throw err;
		});

		function *run() {
		  var nightmare = Nightmare();
		  var title = yield nightmare
			.goto('http://cnn.com')
			.evaluate(function() {
			  return document.title;
			});
		  console.log(title);
		  yield nightmare.end();
		}

is there a way to write the whole code inside X Virtual Frame Buffer, so that we can execute in normal way

    `node cnn.js` instead of `xvfb-run node cnn.js`

**Comment by dingziran** [comment] 2015-12-25 03:01
You can use [headless](https://github.com/kesla/node-headless) to create xvfb child process for you. And get the screen id of background xvfb. Then set DISPLAY=:id to process.env. So then when you start nightmare program, it will find its screen automatically.

**Comment by Ngumbo** [comment] 2016-01-01 17:36
@dingziran can you give an example of how that would look?

**Comment by rosshinkley** [comment] 2016-01-04 22:55
Possible duplicate of #224.

I've had reasonable luck with running `Xvfb` on its own.  See [this comment](https://github.com/segmentio/nightmare/issues/224#issuecomment-141575361) for an example.

**Comment by matthewmueller** [comment] 2016-01-06 19:01
yep, dup of #224

**Closed by matthewmueller** 2016-01-06 19:01 UTC
