### ISSUE TITLE
Electron crashes while generating pdf, no error thrown

### ISSUE THREAD

**Issue by RoryJShevin** [segmentio/nightmare#635] opened 2016-05-13 18:50 UTC
Im using nightmare to turn some large webpages into pdfs and I've been having some issues. After digging around for a bit, here is what I've got.
Generally, everything works, but sometimes I see electron just crash (the process dies) during the pdf generation phase and then nothing else happens. No error is thrown, nightmare never returns anything, promises aren't evaluated. It just stalls out indefinitely. 
I have also seen the same thing happen on occasion with the one difference being the following error
```
Nightmare runner error:
    RangeError: Invalid string length
        at Object.stringify (native)
        at process.target._send (internal/child_process.js:586:23)
        at process.target.send (internal/child_process.js:507:19)
        at EventEmitter.IPC.emitter.emit [as emit] (/Users/roryjesseshevin/Documents/go/src/github.com/parsable/scrivener/node_modules/nightmare/lib/ipc.js:33:15)
        at Function.<anonymous> (/Users/roryjesseshevin/Documents/go/src/github.com/parsable/scrivener/node_modules/nightmare/lib/runner.js:270:14)
```

Any suggestions here?

Edit: Its probably worth noting that I'm not printing directly to a pdf, but storing it as a buffer and passing it along to some compression scripts. 
Also, after playing around with the different debugging options, I got a logline 
`nightmare electron child process exited with code null: undefined +29s`
Edit2: Tried to get some more info out of nightmare when electron crashes. Its shutting down due to the signal SIGILL

**Comment by rosshinkley** [comment] 2016-05-22 16:40
@RoryJShevin Can you post a minimum reproduction of this problem?  Also, what version of Nightmare are you using?

I've tried to reproduce this problem with a ~15mb and ~500mb page and cannot.

**Comment by rosshinkley** [comment] 2016-07-09 17:23
Closing due to lack of information.  If this is still a problem, feel free to reopen/submit a new issue with a repro case.

**Closed by rosshinkley** 2016-07-09 17:23 UTC

**Comment by drnachio** [comment] 2017-03-17 12:18
I have the same problem.
