### ISSUE TITLE
Is it possible to start electron with "xvfb-run electron" through Nightmare ?

### ISSUE THREAD

**Issue by Rayjax** [segmentio/nightmare#228] opened 2015-09-17 08:07 UTC
See stack post http://stackoverflow.com/questions/32612868/running-electron-atom-shell-headlessly-on-linux-server-through-nightmare-js

**Comment by matthewmueller** [comment] 2015-09-19 00:13
Looks like a dup of: https://github.com/segmentio/nightmare/issues/224

**Comment by reinpk** [comment] 2015-09-27 19:18
closing as dupe of #224

**Closed by reinpk** 2015-09-27 19:18 UTC
