### ISSUE TITLE
problem scraping javascript based content

### ISSUE THREAD

**Issue by toppetoppe** [segmentio/nightmare#262] opened 2015-10-01 07:38 UTC
Hi!

Sorry if im doing this wrong but I cant get this to work.

Im trying to extract the following number from a page.
![image](https://cloud.githubusercontent.com/assets/420754/10215197/a4993186-681f-11e5-9514-86a45bafafab.png)
![image](https://cloud.githubusercontent.com/assets/420754/10215222/eeca3dcc-681f-11e5-9f38-2e29852c2977.png)

im using the following code:
```javascript
import vo from 'vo';
import Nightmare from 'nightmare';


const url = 'http://www.jm.se/bostader/sok-bostad/#c=stockholm&ts=allapartmenttypes&vacant=true&tab=objects&listmode=box';
const selector = '#hitcountobjects';

vo(run)(function(err, result) {
  if (err) throw err;
});

function *run() {
  var nightmare = Nightmare();
  var count = yield nightmare
    .goto(url)
    .wait(5000)
    .evaluate(function (selector) {
      // now we're executing inside the browser scope.
      return document.querySelector(selector).innerText;
    }, selector);

  console.log(count);
  yield nightmare.end();
}
```
count is always undefined. Anyone know if this is possible?

**Comment by FdezRomero** [comment] 2015-10-01 16:52
Hi @toppetoppe, I was having some issues with the loading of XHR/AJAX calls and using the option `show: true` when creating the Nightmare instance helped me debug, as you can see the window and how the page is loading with the console on the side.

```javascript
var opts = {
  show: true
};

var nightmare = Nightmare(opts);
```

Hope it helps, maybe you just need to wait longer.

**Comment by toppetoppe** [comment] 2015-10-01 20:55
I see that the text node I want is visible when I set `show = true`but count is still undefined

**Comment by toppetoppe** [comment] 2015-10-08 15:12
anyone got any clue as to why this is not working?

**Comment by FdezRomero** [comment] 2015-10-13 14:44
@toppetoppe This has nothing to do with Nightmare, but have you tried running the code directly in the Dev Tools console? Maybe there is another element matching your selector and `querySelector()` is returning only the first one in the DOM.

**Comment by toppetoppe** [comment] 2015-10-13 14:55
Yeah, I have retrieved the selector using X-ray and that works just fine, but i would prefer to use nightmare.

DevTools console says the following:
![image](https://cloud.githubusercontent.com/assets/420754/10458427/06a92ad4-71cb-11e5-8b83-478d77d7db42.png)

**Comment by FdezRomero** [comment] 2015-10-13 15:07
Then my only theory is that `selector` might not being correctly passed to the function to evaluate. I wonder if you'd be able to double check this by running Nightmare with with `show: true` and then:

```javascript
.evaluate(function (selector) {
  // now we're executing inside the browser scope.
  window.alert(selector); // getting a console.error from Node is doable but harder
  return document.querySelector(selector).innerText;
}, selector);
```

**Comment by toppetoppe** [comment] 2015-10-13 15:13
yeah, looks like that is the problem.
the following does nothing:
```javascript
window.alert(selector)
```

this works.
```javascript
window.alert(document.querySelector('#hitcountobjects').innerHTML); 
```

how should i pass selector to evaluate?

**Comment by FdezRomero** [comment] 2015-10-13 15:36
According to the docs you're doing it right:

```javascript
var selector = 'h1';
var text = yield nightmare
  .evaluate(function (selector) {
    // now we're executing inside the browser scope.
    return document.querySelector(selector).innerText;
   }, selector); // <-- that's how you pass parameters from Node scope to browser scope
```

Probably you should close this issue and open a new one saying that the example in the docs is not working for you, now that you know the cause.

**Comment by reinpk** [comment] 2015-10-25 19:54
@toppetoppe i modified your example slightly and ran it locally:
```js
var vo = require('vo');
var Nightmare = require('nightmare');


var url = 'http://www.jm.se/bostader/sok-bostad/#c=stockholm&ts=allapartmenttypes&vacant=true&tab=objects&listmode=box';
var selector = '#hitcountobjects';

vo(run)(function(err, result) {
  if (err) throw err;
});

function *run() {
  var nightmare = Nightmare({ show: true });
  var count = yield nightmare
    .goto(url)
    .wait(5000)
    .evaluate(function (selector) {
      // now we're executing inside the browser scope.
      return document.querySelector(selector).innerText;
    }, selector);

  console.log(count);
  yield nightmare.end();
}
```

with the following output:
```
(114)
```

**Closed by reinpk** 2015-10-25 19:54 UTC
