### ISSUE TITLE
Nightmare is not able to open Whatsapp web

### ISSUE THREAD

**Issue by lai32290** [segmentio/nightmare#1323] opened 2017-11-20 14:57 UTC
I tried to open Whatsapp web by `Nightmare`, but it's keeping initial loading, it's not able to show up the conversation list and QR code.

I checked the browser's console, but there has no any error.

Someone had same problem? Should I add some option to let it work?

**Comment by blindhover** [comment] 2017-11-22 03:52
nightmare's default preload has prevent 'onunload' and 'onbeforeunload' from being set in the browser.

**Comment by lai32290** [comment] 2017-11-22 09:20
understood, is possible to disable this feature? because I had a look at the [options list](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions), but there has nothing about it.

**Comment by blindhover** [comment] 2017-11-22 09:39
@lai32290 maybe you can just modify the default preload and use it as your own custom version.
have a look at [https://github.com/segmentio/nightmare#custom-preload-script](url)

**Comment by timkock** [comment] 2018-01-14 21:53
@lai32290  this helped #1082

**Comment by matthewmueller** [comment] 2018-02-14 08:41
Duplicate of #1082. I'll make sure we test whatsapp when we fix this.

**Closed by matthewmueller** 2018-02-14 08:41 UTC
