### ISSUE TITLE
`.screenshot` randomly has shadow in first pixel

### ISSUE THREAD

**Issue by rasenplanscher** [segmentio/nightmare#1168] opened 2017-06-23 08:35 UTC
I basically do the following:
```
new Nightmare({
    backgroundColor: '#fff',
    enableLargerThanScreen: true,
    frame: false,
    switches: {
        // prevent high dpi scaling
        'force-device-scale-factor': 1,
        'high-dpi-support': 1,
    },
    thickFrame: false,
    x: 0,
    y: 0,
})
.viewport(width, height)
.wait(waitTime)
.screenshot(screenshotPath)
```

I mostly get the screenshots I want. The background color is `rgb(255, 255, 255)`, but sometimes (on the order of 1 out of 100 runs), the top-left pixel has `rgb(230, 230, 230)`. I have no idea, why, and it seems totally random to me. But it only happens for the first pixel.

Any ideas why this happens and what I can do about it?

**Comment by casesandberg** [comment] 2017-08-23 20:53
Duplicate of https://github.com/segmentio/nightmare/issues/964

**Closed by casesandberg** 2017-08-23 20:53 UTC
