### ISSUE TITLE
Unwanted new-window

### ISSUE THREAD

**Issue by guymorita** [segmentio/nightmare#1196] opened 2017-07-20 05:24 UTC
Expected behavior:
- Authenticate user, click on a menu item to navigate the site as an authed user.

Observed behavior:
- Authenticate user, user nightmare to click on a menu item and a NEW WINDOW is opened. The new window is not authed to the user.

Is there a way to avoid this? It doesn't open a new window while browsing in a normal browser.

Logs:
```
  nightmare:log did-frame-finish-load [{},true] +1s
  nightmare:log did-finish-load [{}] +2ms
  nightmare:log page-favicon-updated [{},["https://xyz.com/wp-content/themes/wp-portal50/favicon.ico"]] +0ms
  nightmare:log did-stop-loading [{}] +0ms
  nightmare:log new-window [{},"https://xyz.com/go/travel.html?cint=tp_regionalactive_envoy","","foreground-tab",{"show":true,"width":800,"height":600,"webPreferences":{"nodeIntegration":false,"openerId":1},"useragent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1588.0 Safari/537.36","waitTimeout":30000,"gotoTimeout":30000,"pollInterval":250,"typeInterval":100,"executionTimeout":30000,"maxAuthRetries":3,"alwaysOnTop":true},[]] +11ms
```

**Comment by casesandberg** [comment] 2017-08-25 00:27
You can use the solution here to stop new windows for opening:

Duplicate of https://github.com/segmentio/nightmare/issues/1071

**Closed by casesandberg** 2017-08-25 00:27 UTC
