### ISSUE TITLE
can't start electron when use webpack

### ISSUE THREAD

**Issue by cucygh** [segmentio/nightmare#997] opened 2017-02-09 10:08 UTC
throw new Error('Electron failed to install correctly, please delete node_modules/' + path.basename(__dirname) + ' and try installing again');

**Comment by vshvydky** [comment] 2017-02-14 21:28
once I had the same question.
But after a certain time with a nightmare, I realized that he was not processed through webpack.
If you want to make your code is not clear, you need to look for other solutions.

**Comment by casesandberg** [comment] 2017-08-22 20:54
This is a duplicate of https://github.com/segmentio/nightmare/issues/719

**Closed by casesandberg** 2017-08-22 20:54 UTC
