### ISSUE TITLE
Event object for .on new-window not working

### ISSUE THREAD

**Issue by amirulshukry** [segmentio/nightmare#1127] opened 2017-05-08 01:24 UTC
When I do this
```
nightmare
  .on('new-window', (event, url) => { 
     event.preventDefault()
     console.log('event: ', event);
     console.log('new window: ', url);
     return false; 
  })
  .goto(URL) // URL that has a pop up new window
```

I get this
```
TypeError: event.preventDefault is not a function
```
nightmare@2.10.0
electron@1.6.6
node v7.9.0

**Comment by sean-hill** [comment] 2017-05-08 18:10
I am facing this same issue.

**Comment by wayne-kim** [comment] 2017-07-07 10:40
I am facing this same issue.

**Comment by casesandberg** [comment] 2017-08-23 19:39
This is a duplicate of https://github.com/segmentio/nightmare/issues/1071

**Closed by casesandberg** 2017-08-23 19:39 UTC
