### ISSUE TITLE
evaluate will sometimes return a boolean - nightmare 2.8.1

### ISSUE THREAD

**Issue by neilwashere** [segmentio/nightmare#868] opened 2016-11-02 16:18 UTC
I can't provide the exact code to reproduce this but I wondered if someone might know why evaluate would return a boolean rather than the expected value (I am assuming this is on the `evaluate` sender and not the `then` receiver).

I have a chain identical to the following sans actual implementation:

````javascript

var evaluateFn = () => {
  var localCollection = [];
  // do some element scraping and push to localCollection
  return localCollection;
}

var resultFn = (someCollection) => {
  // enumerate over the collection
  // ~20% of the time someCollection is a boolean!
}

// browser is set elsewhere
browser.wait("someelem").evaluate(evaluateFn).then(resultFn);
````
localCollection in the `evaluateFn` is *always* as I expect it (console.log shows as much). I realise reproducibility may be an issue but if anyone can offer some guesses, I'd take that :)

**Comment by rosshinkley** [comment] 2016-11-04 03:32
I gave this a try with the following script:
```js
var nightmare = require('nightmare')();

var evaluateFn = () => {
  var localCollection = localCollection = [1,true,"hello",4.5,{some:"thing"}];
  return localCollection;
};
var resultFn = (someCollection) => {
  console.dir(someCollection);
};

nightmare
  .goto('http://example.org')
  .evaluate(evaluateFn)
  .then(resultFn)
  .then(() => nightmare.end().then());
  ```
... and ran it with `for i in `seq 1 100`; do node script.js; done` to simulate running it 100 times.  I couldn't reproduce this behavior.

Does your function _always_ return `localCollection`?  Is that array actually an array, or can it possibly be something like a DOM list?

**Comment by neilwashere** [comment] 2016-11-04 11:28
Thanks for getting back to me. I am 100% sure the results are always an array. I am sorry that I can't provide some more concrete code but I do have some more news.

I can't hammer the site in question that I am polling but I have just run 80 requests over a period of time, in batches of 20, with and without the electron browser - so run 20 with then 20 without, repeat. The failure rate due to `evaluate` returning a boolean (or `then` thinking it has one) are as follows:

try 1 - show true: 30%
try 2 - show false: 0%
try 3 - show true: 15%
try 4 - show false: 0%

Now, I can't replicate this against a strait forward content site. The site I am scraping has all kinds of quirks and is fairly complex - one end to end request is in the region of 10 seconds (to return a very small array of results - each result is a simple object of about 7 properties with string values and to date only one result in the array).

Does that provide any more clues? could it be that the evaluate block times out somehow - returning the status of the evaluation but not the results? (I am reaching here, apologies). 

Cheers

**Comment by neilwashere** [comment] 2017-03-23 10:41
After running into several more of these it turns out the behavior is more prevalent when running concurrent sessions. This is related to https://github.com/segmentio/nightmare/issues/727

**Comment by casesandberg** [comment] 2017-08-22 20:04
Go ahead and try out the headless Chrome implementation in v3, it might solve this error for you! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if it's still an issue.

**Closed by casesandberg** 2017-08-22 20:04 UTC

**Comment by phamhathanh** [comment] 2020-06-30 15:25
I also encountered the same problem in v3.0.2
It seems to occur when multiple `evaluate`s and/or `wait`s are running concurrently.

I was able to reproduce the issue using the following code
```js
let Nightmare = require('nightmare');

async function main() {
  let nightmare = new Nightmare({ show: true });
  await nightmare.goto('https://duckduckgo.com');

  let results = await Promise.allSettled([
    nightmare.evaluate(() => 33333),
    nightmare.evaluate(() => 44444),
    nightmare.evaluate(() => 'foo'),
  ]);
  console.log(results.map(result => result.value));
  // Expect: [33333, 44444, 'foo']
  // Actual: ['foo', undefined, undefined]
  await nightmare.wait(50000);
}

main();
```
