### ISSUE TITLE
Why nightmarejs can't run correctly in ubuntu & centos?

### ISSUE THREAD

**Issue by YueShuXie** [segmentio/nightmare#423] opened 2016-01-02 02:16 UTC
I found that the Examples <<Let's search on Yahoo:>> can't run correctly in ubuntu & centos. When I run the examples in window 8, It's can run and output the result. But when I run the examples in ubuntu & centos, it run fast and exit at once, and no result output. It seems like that nightmare just push action into queue, but do nothing.

Can anybody else have such issues?

**Comment by YueShuXie** [comment] 2016-01-02 02:41
output in window8:
----------------------------------------------------------------
> node yahoo.js

https://github.com/segmentio/nightmare





output in centos:
----------------------------------------------------------------
[root@test]# DEBUG=nightmare node --harmony yahoo.js   
nightmare starting...                                        
  nightmare queueing action "goto" for http://yahoo.com +0ms 
  nightmare queueing action "type" +5ms                      
  nightmare queueing action "click" +2ms                     
  nightmare queueing action "wait" +0ms                      
  nightmare queueing action "evaluate" +0ms                  
  nightmare running +1ms

**Comment by rosshinkley** [comment] 2016-01-04 22:50
Without spinning up a Centos VM, this sounds suspiciously like there's no X-compatible framebuffer running.  Take a look through #224, possible duplicate of #269.

**Comment by YueShuXie** [comment] 2016-01-06 13:43
Thank you very much. 
I have take a look through #224, and make some upgrade for my ubuntu server.
Now my program has been running in ubuntu correctly.

Thank you!

**Comment by matthewmueller** [comment] 2016-01-06 19:00
closing since this is a dup of #224

**Closed by matthewmueller** 2016-01-06 19:00 UTC
