### ISSUE TITLE
Improve error handling when trying to return dom elements from evaluate

### ISSUE THREAD

**Issue by nguyenchr** [segmentio/nightmare#862] opened 2016-10-31 20:09 UTC
Node Version: 4.2.3
Nightmare Version: 2.8.1
Mocha Version: 3.1.2

I was initially trying to return the result of a `document.querySelectorAll` query in the `evaluate`
I now know that I shouldnt be doing this but I would expect something more descriptive than a timeout

using the following command `mocha index.js`

The following code will just hang and timeout, I would expect the `then` function to be called with an empty object or null

```js
var Nightmare = require('nightmare')

describe('Nightmare', function() {
  it('should not hang', function(done) {
      this.timeout(20000)
      Nightmare()
        .goto('http://www.muzeroom.com/')
        .wait('.story-list-item')
        .evaluate(function () {
          return document.querySelectorAll('.story-list-item')
        })
        .end()
        .then(function(result) {
          console.log('in the then ', result)
          done();
        })
        .catch(function(err) {
          console.log('in the catch', err.message)
          done()
        })
    });
});
```

but this code will successfully return the textContent (which leads me to believe that the `wait` and `querySelectorAll` are working correctly

```js
var Nightmare = require('nightmare')

describe('Nightmare', function() {
  it('should not hang', function(done) {
      this.timeout(20000)
      Nightmare()
        .goto('http://www.muzeroom.com/')
        .wait('.story-list-item')
        .evaluate(function () {
          return document.querySelectorAll('.story-list-item')[0].textContent
        })
        .end()
        .then(function(result) {
          console.log('in the then ', result)
          done();
        })
        .catch(function(err) {
          console.log('in the catch', err.message)
          done()
        })
    });
});

```

**Comment by Mr0grog** [comment] 2016-11-01 20:54
Quick notes before I have to stop looking at this for now:

1. The problem is in the IPC between the Electron process itself and the browser window process when JS is evaluated (i.e. in `win.webContents.executeJavaScript()`).

2. In @nguyenchr’s example above, the specific issue isn’t in the DOM node but in the jQuery metadata attached to it. Most specifically, it’s an AngularJS `$scope` object attached to the node, which is both very deep and highly recursive.

3. Looks like this was *most likely* caused by changes to the recursion/uniqueness checking algorithm in Electron’s JS <-> C++ conversion code (which is how values get packaged up for IPC) here: https://github.com/electron/electron/pull/6977

4. There’s an Electron issue tracking it: https://github.com/electron/electron/issues/7286

Not sure if there are also things worth doing in Nightmare ahead of Electron improving on their side:

- Detect recursion and just disallow it? e.g. something like `JSON.parse(JSON.stringify(returnValue))` will throw [quickly] when recursion is encountered, though this could cause other issues :\
- Special case DOM nodes and just send back some particular meaningful properties and NOT metadata attached to them? Or send back an error instead for DOM nodes? (This won’t fix the real issue of sending deep/recursive data structures, but would make it less likely to happen.)

**Comment by rosshinkley** [comment] 2016-11-04 02:53
@Mr0grog Would it be worth it to use something like [`json-stringify-safe`](https://www.npmjs.com/package/json-stringify-safe) to handle circular references when serializing data to pass over the IPC boundary?

**Comment by Mr0grog** [comment] 2016-11-04 18:29
> Would it be worth it to use something like json-stringify-safe to handle circular references

I’d like to think no—the code that seems to be the culprit for the hang (introduced in Electron 1.3.5) is the code that is meant to null out circular refs and basically do exactly what json-stringify-safe does but without stringifying. Seems like it would be better to get that fixed at the source.

**Comment by casesandberg** [comment] 2017-08-23 19:55
Do you have some time to throw together a PR for this? I would be happy to take a look at it. I am going to close this, but feel free to open a new issue.

**Closed by casesandberg** 2017-08-23 19:55 UTC

**Comment by Mr0grog** [comment] 2017-09-03 05:31
Aight, I missed this note while traveling. Sorry, @casesandberg. I think I'm removed enough in time from this that I no longer have a great sense on what the right fix is. The “easy” solution here is probably to return some stand-in data for a DOM node, but it's an open question what the right stuff to return is. It's also not the actual issue (and we should check whether Electron has improved it in the past year anyway).

I'm also not sure this makes a whole lot of sense to work on since you're rewriting everything to not run on Electron. That said, people trying to return DOM nodes, which will never work right over any kind of IPC, will still be a common problem. Might make sense to hash out what you think a good solution for this ought to be. Or rather, this issue deserves some thinking and discussion before implementation.
