### ISSUE TITLE
Custom action dont works

### ISSUE THREAD

**Issue by necromind** [segmentio/nightmare#959] opened 2017-01-16 16:37 UTC
Code from here: https://github.com/segmentio/nightmare/issues/887#issuecomment-269412280

```js
Nightmare.action('sendKeyPress',
  function(name, options, parent, win, renderer, done) {
    parent.respondTo('sendKeyPress', function(unicodeValue, done) {
      win.focus();
      win.webContents.sendInputEvent({
        type: "keyDown",
        keyCode: unicodeValue,
      });
      setTimeout(() => {
        win.webContents.sendInputEvent({
          type: "keyUp",
          keyCode: unicodeValue,
        });
        done();
      },50);
    });
    done();
  },
  function(unicodeValue, done) {
    this.child.call('sendKeyPress', unicodeValue, done);
  });

	nightmare
		//.cookies.clearAll()
		.viewport(1280, 1024)
		.goto('https://url/')
		.sendKeyPress('\u202D')
		.run();
```

And i have error: 
```
return fn.apply(self, doneargs);
             ^
TypeError: Cannot read property 'apply' of undefined
```
Why dont works? This is like example from main wiki "Defining a custom action with an Electron method"

**Comment by necromind** [comment] 2017-01-16 16:58
Solved. done must be first: 
```js
  function(done, unicodeValue) {
    this.child.call('sendKeyPress', unicodeValue, done);
  });
```

But this code anyway dont send press right key event.

**Comment by necromind** [comment] 2017-01-18 10:16
```js
var Nightmare = require('nightmare');


Nightmare.action('clearCache',
  function(name, options, parent, win, renderer, done) {
    parent.respondTo('clearCache', function(done) {
      //win.webContents.session.clearCache(done);
    });
    done();
  },
  function(message,done) {
    this.child.call('clearCache', done);
  });

  var  nightmare = Nightmare(
      {
        show: true
      });

  nightmare
    //go to a url
    .goto('ulr')
    //clear the cache
    .clearCache()
    .wait(3000)
    //go to another url
    .goto('http://ya.ru')
    //perform other actions
    .then(() => {
      //...
    })
    //... other actions...
    //.then(nightmare.end())
    .catch((e) => console.dir(e));
```

This code from examples dont work too! App sleeps at clearCache point. HOW can i get access to **win.webContents** for using sendInputEvent. Help me pls.

**Comment by rosshinkley** [comment] 2017-01-20 20:43
Your `clearCache` method takes a `message` parameter, but you're not passing anything to the call in your Nightmare chain.  What happens if you try changing `function(message, done)` to just `function(done)`?

**Comment by gneccao** [comment] 2017-01-23 21:52
i have the same problem with the custom actions. 
I'm using the 2.9.1 and still have the problem for me.

**Comment by contobob** [comment] 2017-02-07 14:59
+1. No custom action works for me either if it involves interacting with electron.

I can't even get the `clearCache` custom action from [the documentation](https://github.com/segmentio/nightmare#nightmareactionname-electronactionelectronnamespace-actionnamespace) to work.

Here's a test script (copy-pasted clearCache from doc):
```node.js
var Nightmare = require('nightmare');
Nightmare.action('clearCache',
    function(name, options, parent, win, renderer, done) {
        parent.respondTo('clearCache', function(done) {
            win.webContents.session.clearCache(done);
        });
        done();
    },
    function(done) {
        this.child.call('clearCache', done);
    });

var nightmare = Nightmare({
    show: true,
    electronPath: require('electron'),
});

nightmare
    .clearCache()
    .goto('http://google.com')
    .evaluate(function () {
        return document.title;
    })
    .end()
    .then(function (result) {
        console.log(result);
    })
    .catch(function (error) {
        console.error('Retrieve title failed:', error);
    });
```

What happens when I run `node actionstest.js`: a blank electron window opens up. Nightmare then stalls on the white page until I quit the script via `ctrl-c`.

Full output for `DEBUG=nightmare:*,electron:* node actionstest.js` (it stalls immediately after):

```
  nightmare:log adding action for clearCache +0ms
```

Nightmare verision `2.9.1`.
Electron version `1.5.0`.
Unlikely related but: macOS Sierra 10.12.2.

Any help here would be greatly appreciated.

The bug, whatever it is, renders all custom actions useless, including [kyungw00k/nightmare-webrequest-addon](https://github.com/kyungw00k/nightmare-webrequest-addon) and [rosshinkley/nightmare-load-filter](https://github.com/rosshinkley/nightmare-load-filter).

**Comment by rosshinkley** [comment] 2017-02-10 03:36
@contobob What you have there will almost certainly not work: `win.webContents.session` does not exist until you navigate away from `default:blank`.  (Why would you try to clear a session cache before it exists?)

If you're having problems with those plugins, i would encourage you to open issues there.

**Comment by contobob** [comment] 2017-02-10 14:30
Thanks for the reply @rosshinkley. Does that mean the docs in README.md should be updated? My test code was mainly a copy-paste of what can be found [here](https://github.com/segmentio/nightmare#nightmareactionname-electronactionelectronnamespace-actionnamespace) in the `clearCache` example. The doc puts `clearCache` before `goto`.

**Comment by ysimonson** [comment] 2017-02-13 19:54
Having the same issue. This is almost a copy-paste from the readme:

```javascript
Nightmare.action('clearCache',
  function(name, options, parent, win, renderer, done) {
    parent.respondTo('clearCache', function(done) {
      win.webContents.session.clearCache(done);
    });
    done();
  },
  function(done) {
    this.child.call('clearCache', done);
  });

var nightmare = Nightmare({
    show: true,
    webPreferences: {
        partition: 'testaction'
    }
});

nightmare
  .clearCache()
  .goto('http://example.org')
  .then(function() {
    console.log("done");
    process.exit(0);
  });
```

However, it works fine if you remove the bits that call/declare the action:

```javascript
var nightmare = Nightmare({
    show: true,
    webPreferences: {
        partition: 'testaction'
    }
});

nightmare
  .goto('http://example.org')
  .then(function() {
    console.log("done");
    process.exit(0);
  });
```

**Comment by ysimonson** [comment] 2017-02-14 14:36
It's not an issue strictly with the placement of `clearCache` - granted that's probably wrong, even though it's in the readme. If you call `goto` before `clearCache`, it'll never get past `clearCache` - i.e. in this example, it'll print A, but not B or C.

```javascript
Nightmare.action('clearCache',
  function(name, options, parent, win, renderer, done) {
    console.log("B");
    parent.respondTo('clearCache', function(done) {
      console.log("C");
      win.webContents.session.clearCache(done);
    });
    done();
  },
  function(done) {
    console.log("A");
    this.child.call('clearCache', done);
  });

var nightmare = Nightmare({
    show: true,
    webPreferences: {
        partition: 'testaction'
    }
});

nightmare
  .goto('http://example.org')
  .clearCache()
  .then(function() {
    console.log("done");
    process.exit(0);
  });
```

**Comment by ogoid** [comment] 2017-02-19 15:03
It's definitely not a problem with the browser cache. Here is a test case with logging only; seems inChild is never called:

```javascript
Nightmare = require('nightmare')

inChild = function(name, options, parent, win, renderer, done) {
  console.log('inChild')
  parent.respondTo('testAction', function(done) {
    console.log('it works!')
    done()
  })
  done()
}

inParent = function(done) {
  console.log('inParent')
  this.child.call('testAction', done)
}

Nightmare.action('testAction', inChild, inParent)

Nightmare({show: true, alwaysOnTop: false})
  .goto('http://httpbin.org/get')
  .testAction()
  .then(console.log)
  .catch(console.error)
```

**Comment by rosshinkley** [comment] 2017-02-24 03:05
@ysimonson It _does_ print B and C, just not to `stdout` of the node process.  Instead, those get printed (rightfully) to Electron's `stdout`.  Consider your above script, but instead of running with `node example.js` you run with `DEBUG=electron* node example.js`.  You'll see the following output:

```
  electron:stdout B +0ms
A
  electron:stdout C +358ms
```

... which is precisely what you would expect to see.  `B` when the action is created on the instance, followed by `A` when the action is called, followed by `C` when the action responds to the call.

**Comment by rosshinkley** [comment] 2017-02-24 03:14
Bah, I realized I didn't answer the question of why it's not calling back: It looks like the clearCache callback isn't getting called.  I'll dig into that.

**Comment by entrptaher** [comment] 2017-03-12 17:04
@rosshinkley Have a look into this, its been several months since we've found such issue. Nothing responds to such actions. :/ 

![screenshot from 2017-03-12 22-59-35](https://cloud.githubusercontent.com/assets/8284972/23833958/328e77b4-0778-11e7-8106-fe6d1e8287a6.png)

**Comment by rosshinkley** [comment] 2017-03-17 04:07
In this particular case, it looks like `webContents.session.clearCache` never calls back, and it's not immediately clear why.  I'm inclined to say this is a bug with Electron: the source for [`clearCache`](https://github.com/electron/electron/blob/7f7df5a6dd083117bfa8175bf3ce1d52771eea6a/atom/renderer/api/atom_api_web_frame.cc#L236-L241) does not have a callback call, at least in my cursory look.  For contrast, compare that to [`clearStorage`](https://github.com/electron/electron/blob/bad130f623d1ed0de1a61bc3e82ae553fbf46364/atom/browser/api/atom_api_session.cc#L505) that does.

If you move the `done` call to the line after `clearCache`, does the cache actually clear?  This may be worth opening with Electron.  Thoughts?

**Comment by aight8** [comment] 2017-03-27 01:14
Please Fix

**Comment by entrptaher** [comment] 2017-03-27 03:09
@rosshinkley If you create custom actions, almost same kind of error happens no matter the callback.

**Comment by aight8** [comment] 2017-03-27 03:39
**IMPORTANT** I hope I can help - spend some hours on it now.
- the action registration must be **BEFORE** you create your nightmare instance.
- if you access for example the ```win.webContents.session``` property you must call the plugin after a page is loaded (means for example **AFTER** the ```goto```) - @entrptaher in your code this could be the problem how I see on the screen shot. The problem is that it fails silently because exceptions are not reported which are throwed electron side. (see below to improve this)

To this package to improve:

- ```console.*``` calls in "children function" (which run on electron children process) should be redirected also to the main process output - it's hard to debug otherwise if you don't know that ```parent.emit('log', 'my_value')``` exists, also it depends on the DEBUG var - don't forget it (```DEBUG=* node srv.js```)
- Exceptions on electron side should be catched and redirected to the client and throwed there again with a note that it happened on electron side. Currently it crashes without infos.
- The ```Nighmare.action``` interface to register action is weird because of it's (name[, childFn], parentFn) signature. It must be clarified what the "child" and "parent" process are - and the optional value should be at the end - I can imagine the reason was the order, whyever - it's really more confusing. I just say:

```
  var name = arguments[0], childfn, parentfn;
  if(arguments.length === 2) {
    parentfn = arguments[1];
  } else {
    parentfn = arguments[2];
    childfn = arguments[1];
  }
```

- The API documentation has following flaws:
   - definitely missing of an overview - a simply TOC could help so much for orientation
   - document the rest of the members of the nightmare object
- I saw that ```@types/nightmare``` is currently on version 1.6, older than 2 years. This package has over 11k stars. No TS users here? I wrote the whole definition, very neat and complete. I will spend some time to prepare and publish it on @types if there are people who are interested for it, but if there are 12k js only users its okey.

**Comment by entrptaher** [comment] 2017-03-27 03:49
Custom actions worked if I used it after a goto, but sometimes you need actions to do before going to any url. But what more important is that **all examples** from the docs are not working properly. Any action after goto works and any action before goto simply fails.

**Comment by aight8** [comment] 2017-03-27 03:51
Yes I know they should be removed all, temporarily. Currently not examples but broken code.

**Comment by entrptaher** [comment] 2017-03-27 03:59
This is what I had to do with all `done()` functions to make it working.
Example code: https://gist.github.com/entrptaher/870246d824c10317edf72a0d4b86760e

**Comment by rosshinkley** [comment] 2017-03-27 21:50
>Custom actions worked if I used it after a goto, but sometimes you need actions to do before going to any url.

I think I understand what the problem is now after seeing your example.  When `Nightmare.action()` (on the prototype) is called, there's an action put on the prototypal queue to execute action methods on all created instances.  Looking at your gist, it occurs to me there might be a bug when immediately calling a plugin method.  Poking around in the unit tests for Nightmare, I don't think this particular case is tested for and is probably worth adding to at least prove out that's not the problem.

> Exceptions on electron side should be catched and redirected to the client and throwed there again with a note that it happened on electron side. Currently it crashes without infos.

This is a somewhat complicated topic.  See #646.

> ...and the optional value should be at the end - I can imagine the reason was the order, whyever...

This is because `.action()` already existed, and I wanted to have as much backwards compatibility with previous versions as possible.

> The API documentation has following flaws:

You missed a few. ;)  Kidding aside, this has been on my backburner for a long time - it's why [`nightmare-examples`](https://github.com/rosshinkley/nightmare-examples) exists.  I'd _like_ for this to all be wrapped up on github pages, but I haven't made it that far yet.

>I saw that @types/nightmare is currently on version 1.6, older than 2 years.

PR DefinitelyTyped?

> If you create custom actions, almost same kind of error happens no matter the callback.

I don't think that's true as there are a _lot_ of plugin libraries that use this.  That said, I'm _almost positive_ you've hit a bug with either how caching works in Electron and/or with how actions are created on the instance after Electron is started.

**Comment by SkyHacks** [comment] 2017-04-04 23:31
I was running into an issue where my custom Electron actions were being defined _after_ the instance was created. Moving those up fixed the issues I was having. Just FYI to anyone who makes the same mistake.

**Comment by casesandberg** [comment] 2017-08-23 19:36
Looks like this is resolved. There are a couple of points of things to improve but those should be opened as separate issues. I am going to close this for now but feel free to open a new issue if you are still having problems.

**Closed by casesandberg** 2017-08-23 19:36 UTC

**Comment by rinogo** [comment] 2019-09-26 22:45
As @entrptaher [mentioned](https://github.com/segmentio/nightmare/issues/959#issuecomment-289348654), since [the clearCache callback isn't getting called](https://github.com/segmentio/nightmare/issues/959#issuecomment-282192517), "manually" calling `done()` seems to fix the problem. However, couldn't that potentially mess up timing for subsequent requests?

On a "fast" machine, it seems to me that some of the first subsequent HTTP requests would still use the cache, and then once clearCache had actually cleared the cache (at some non-deterministic time), HTTP requests would actually be performed since the cache would finally be empty. Right? Or am I misunderstanding something?
