### ISSUE TITLE
Deployable to Heroku?

### ISSUE THREAD

**Issue by kanethal** [segmentio/nightmare#497] opened 2016-02-23 03:54 UTC
Anyone have experience deploying nightmare.js to run on heroku? Curious if I should anticipate any problems.

**Comment by yoz** [comment] 2016-02-23 04:14
Yes, it's possible but somewhat complicated because of the limitations of the Heroku environment.

You will need Xvfb for a virtual framebuffer. It doesn't work out of the box on Heroku, so it needs some patching. You also may run into an issue with /dev/shm being too small, which manifests itself as Electron crashing after a few operations in Nightmare. This is fixed in a very recent Chromium (m49) so I'm not sure when it will be reflected in Electron (http://electron.atom.io/#electron-versions).

Here are some relevant links:

- https://github.com/segmentio/nightmare/issues/224
- http://stackoverflow.com/questions/28687120/is-it-possible-to-run-xvfb-on-heroku/
- https://bugs.chromium.org/p/chromium/issues/detail?id=522853

**Comment by kanethal** [comment] 2016-02-23 04:40
Thank you so much for that. Can you by chance recommend a cloud solution that might work better?

**Comment by yoz** [comment] 2016-02-23 18:36
Not specifically, but one that gives you full control over a VM would make it easier (you'd only have to install Xvfb via your distro package manager).

**Comment by rosshinkley** [comment] 2016-03-30 03:28
Closing as (at least a partial) duplicate of #224.

**Closed by rosshinkley** 2016-03-30 03:28 UTC

**Comment by ianstormtaylor** [comment] 2017-05-22 22:30
FWIW for future people, I was never able to get Nightmare working on Heroku's `heroku-16` stack, and just kept getting this error that I couldn't fix:

```
Xvfb: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
xvfb-run: error: Xvfb failed to start
```

If you're running into that, try specifically setting the stack to `cedar-14`, either in `app.json` or with the Heroku CLI.

**Comment by oscarmorrison** [comment] 2017-06-13 02:42
For anyone still having trouble (I wasted 10+hours on this) I made a starter repo with a working setup and instructions for deploying on heroku: https://github.com/oscarmorrison/nightmare-heroku

**Comment by lamkent00** [comment] 2017-06-20 10:50
Hi @oscarmorrison , I try to deploy your repo on heroku but not work. Can you help me to fix it ? Tks so much :)
2017-06-20T10:30:44.000000+00:00 app[api]: Build succeeded
2017-06-20T10:32:21.915526+00:00 heroku[web.1]: Starting process with command `npm start`
2017-06-20T10:32:25.326127+00:00 app[web.1]:
2017-06-20T10:32:25.326139+00:00 app[web.1]:
2017-06-20T10:32:25.326138+00:00 app[web.1]: > life-scrape@1.0.0 start /app
2017-06-20T10:32:25.326139+00:00 app[web.1]: > node index.js
2017-06-20T10:32:25.460334+00:00 app[web.1]: Welcome to Nightmare scrape
2017-06-20T10:32:25.460337+00:00 app[web.1]: ==========
2017-06-20T10:32:25.668949+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-20T10:32:25.670036+00:00 heroku[web.1]: State changed from crashed to starting
2017-06-20T10:32:25.657269+00:00 heroku[web.1]: Process exited with status 0
2017-06-20T10:32:39.130578+00:00 heroku[web.1]: Starting process with command `npm start`
2017-06-20T10:32:42.619879+00:00 heroku[web.1]: Process exited with status 0
2017-06-20T10:32:42.338382+00:00 app[web.1]:
2017-06-20T10:32:42.338400+00:00 app[web.1]: > node index.js
2017-06-20T10:32:42.338399+00:00 app[web.1]: > life-scrape@1.0.0 start /app
2017-06-20T10:32:42.338401+00:00 app[web.1]:
2017-06-20T10:32:42.525333+00:00 app[web.1]: Welcome to Nightmare scrape
2017-06-20T10:32:42.525338+00:00 app[web.1]: ==========
2017-06-20T10:32:42.632560+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-20T10:34:59.664287+00:00 heroku[web.1]: State changed from crashed to down
2017-06-20T10:34:59.447446+00:00 app[api]: Scaled to web@0:Free worker@1:Free by user kentphan239@gmail.com
2017-06-20T10:35:11.337798+00:00 heroku[worker.1]: Starting process with command `DEBUG=* xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" node --harmony index.js`
2017-06-20T10:35:12.035142+00:00 heroku[worker.1]: State changed from starting to up
2017-06-20T10:35:14.096867+00:00 heroku[worker.1]: Process exited with status 1
2017-06-20T10:35:13.966988+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:13 GMT nightmare queuing process start
2017-06-20T10:35:13.973495+00:00 app[worker.1]: Welcome to Nightmare scrape
2017-06-20T10:35:13.974287+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:13 GMT nightmare queueing action "goto" for http://blog.oscarmorrison.com/nightmarejs-on-heroku-the-ultimate-scraping-setup/
2017-06-20T10:35:13.973497+00:00 app[worker.1]: ==========
2017-06-20T10:35:13.974383+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:13 GMT nightmare queueing action "wait"
2017-06-20T10:35:13.974454+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:13 GMT nightmare queueing action "evaluate"
2017-06-20T10:35:13.975153+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:13 GMT nightmare running
2017-06-20T10:35:14.000336+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:14 GMT electron:stderr /app/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
2017-06-20T10:35:14.003192+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:14 GMT nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly
2017-06-20T10:35:14.003865+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:14 GMT nightmare electron child process not started yet, skipping kill.
2017-06-20T10:35:14.108765+00:00 heroku[worker.1]: State changed from up to crashed
2017-06-20T10:35:14.109368+00:00 heroku[worker.1]: State changed from crashed to starting
2017-06-20T10:35:26.397000+00:00 heroku[worker.1]: Starting process with command `DEBUG=* xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" node --harmony index.js`
2017-06-20T10:35:27.106393+00:00 heroku[worker.1]: State changed from starting to up
2017-06-20T10:35:28.712173+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:28 GMT nightmare queuing process start
2017-06-20T10:35:28.719479+00:00 app[worker.1]: Welcome to Nightmare scrape
2017-06-20T10:35:28.719482+00:00 app[worker.1]: ==========
2017-06-20T10:35:28.720612+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:28 GMT nightmare queueing action "goto" for http://blog.oscarmorrison.com/nightmarejs-on-heroku-the-ultimate-scraping-setup/
2017-06-20T10:35:28.720755+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:28 GMT nightmare queueing action "wait"
2017-06-20T10:35:28.720869+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:28 GMT nightmare queueing action "evaluate"
2017-06-20T10:35:28.721812+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:28 GMT nightmare running
2017-06-20T10:35:28.749373+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:28 GMT electron:stderr /app/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
2017-06-20T10:35:28.752941+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:28 GMT nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly
2017-06-20T10:35:28.753756+00:00 app[worker.1]: Tue, 20 Jun 2017 10:35:28 GMT nightmare electron child process not started yet, skipping kill.
2017-06-20T10:35:28.852396+00:00 heroku[worker.1]: State changed from up to crashed
2017-06-20T10:35:28.839294+00:00 heroku[worker.1]: Process exited with status 1
2017-06-20T10:36:15.487448+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=nightmareheroku.herokuapp.com request_id=95f37371-f8c4-4ec6-a7ff-759c5a2ea7d0 fwd="117.3.64.66" dyno= connect= service= status=503 bytes= protocol=https
2017-06-20T10:36:16.921394+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=nightmareheroku.herokuapp.com request_id=6b872cf5-5c4b-4bc0-9c16-76c798d7effefwd="117.3.64.66" dyno= connect= service= status=503 bytes= protocol=https

C:\Users\LamKent\Google Drive\HEROKU\nightmare-heroku>`

**Comment by leviwheatcroft** [comment] 2017-08-05 08:47
@lamkent00 I think your issue [has been solved](https://github.com/oscarmorrison/nightmare-heroku/issues/2) (something to do with dependencies)

@oscarmorrison thanks, your 10 hours might have felt like a waste, but it saved me (and I'm sure others) all that time (and probably much more). Love your work mate.

**Comment by JordanDDisch** [comment] 2017-08-29 03:15
Has anyone tried to run nightmare with Heroku CI. I'm trying to do UAT tests with nightmare with https://github.com/oscarmorrison/nightmare-heroku

**Comment by ubuntugod** [comment] 2018-04-04 15:55
This is what I get after deploying [https://github.com/oscarmorrison/nightmare-heroku](https://github.com/oscarmorrison/nightmare-heroku):

`nightmare queueing action "goto" for http://blog.oscarmorrison.com/nightmarejs-on-heroku-the-ultimate-scraping-setup/ +11ms
  nightmare queueing action "wait" +1ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +2ms
  electron:stderr /app/node_modules/electron/dist/electron: symbol lookup error: /app/node_modules/electron/dist/electron: undefined symbol: _ZN12v8_inspector8protocol8Debugger3API6Paused10ReasonEnum3XHRE +161ms
  nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly +11ms
  nightmare electron child process not started yet, skipping kill. `

This is display when I execute the code as `heroku run DEBUG=nightmare*,electron:* node --harmony index.js`

**Comment by koonse** [comment] 2024-09-03 15:03
@oscarmorrison  @ianstormtaylor Have you recently deployed / maintained Xvfb on Heroku? .. I'm trying now to get it to work and going crazy all weekend long .. I'm not using Nightmare, but it feels like one 😄  (I'm trying to get Playwright to work and need a virtual frame buffer)
