### ISSUE TITLE
Cannot use nightmare inside an electron app

### ISSUE THREAD

**Issue by mping** [segmentio/nightmare#856] opened 2016-10-27 15:08 UTC
Tried to use it within an (cljs) electron app, and when nightmare requires electron the return value is an object instead of being a string pointing to the electron binary. I guess that this is because it has already been loaded.

When the spawn call occurs, it will never work because `electron_path` is borked.

**Comment by entrptaher** [comment] 2016-10-28 21:04
Maybe you can do something like this in a electron resources/app folder. I mainly do it for a lot of apps. Might be unrefined, but it has been the fastest way for me till now.

### Make a folder structure like this, you already know how this is.
![](http://i.imgur.com/1lAUF9M.png)

### The package.json file can just have the nightmare as module. Just run `npm i` in current ***resources/app*** folder

`
$ cat package.json
`
```js
{
  "name": "nightmarify",
  "version": "0.1.5",
  "description": "Nightmare Along With Electron",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "entrptaher",
  "license": "ISC",
  "dependencies": {
    "nightmare": "^2.5.3"
  }
}
```
### This file can be just the js file needed for a normal electron app. 
`
$ cat index.js
`
```js
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow
let mainWindow

function createWindow() {
    mainWindow = new BrowserWindow({
        title: "Dummy",
        fullscreenable: false,
        resizable: false,
        alwaysOnTop: false,
        width: 420,
        height: 250,
        'web-preferences': {
            'web-security': false
        }
    })
    mainWindow.loadURL(`file://${__dirname}/index.html`)
    mainWindow.on('closed', function() {
        mainWindow = null
    })
}

app.on('ready', createWindow)
app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})
app.on('activate', function() {
    if (mainWindow === null) {
        createWindow()
    }
})
```
### And finally the index.html file with our magic script tags.
```html
I'll search for something on yahoo and show it below.
<br>
<b id="results"></b>

<script>
// Yes this is a copy from nightmare docs except the result and the show part
// This script goes to youtube and returns the link to the first result of specific search phrase
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: false });

nightmare
  .goto('http://yahoo.com')
  .type('form[action*="/search"] [name=p]', 'github nightmare')
  .click('form[action*="/search"] [type=submit]')
  .wait('#main')
  .evaluate(function () {
    return document.querySelector('#main .searchCenterMiddle li a').href
  })
  .end()
  .then(function (result) {
    document.getElementById("results").innerHTML = result;
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
  // I can do it like this too... 
 // require("../nightmare/nightmare.js")
</script>
```

The result is something like this.
![](http://i.imgur.com/ERVsi62.png)

I don't know if this is what you want, but I hope it helps you.

**Comment by mping** [comment] 2016-10-31 09:37
I was setting the `electronPath` manually, will give it a shot later. Thanks

**Comment by josephrocca** [comment] 2016-12-04 12:27
Would be great if nightmare.js had official support for this. Is it technically feasible? Like, and option to pass  an existing electron instance into the nightmare.js constructor? I don't know much about the inner workings of this stuff, so please excuse my ignorance.

**Comment by mping** [comment] 2016-12-07 17:22
@entrptaher I did something similar to the stuff that you mentioned and it worked. Basically added a `package.json` in resources folder and put electron there, and installed the node module.

**Comment by Overtorment** [comment] 2017-03-12 00:18
This might help someone...
I managed to run `Nightmare` inside `Electron` using mentioned `package.json` with `nightmare` depencancy in `app` folder, and initing Nightmare like this:

```js
      var nightmare = Nightmare({
        electronPath: require('./node_modules/nightmare/node_modules/electron'),
      })
```

**Comment by entrptaher** [comment] 2017-03-12 00:21
@Overtorment Here is another random issue related to that.
https://github.com/segmentio/nightmare/issues/1018

**Comment by codeofsumit** [comment] 2017-05-21 14:24
@Overtorment I don't quite get what the solution is. I got the same issue but with your solution, I get 
`Error: Cannot find module './node_modules/nightmare/node_modules/electron'`.

What steps do I have to follow to make this work?

**Comment by entrptaher** [comment] 2017-05-21 19:07
@codeofsumit how about trying something like this?

```
electronPath: require(`${__dirname}/../node_modules/electron`)
```

**Comment by codeofsumit** [comment] 2017-05-21 19:12
`electronPath: require('./node_modules/electron'),`

👆  this worked :)

**Comment by NahroTo** [comment] 2017-06-09 03:25
Thanks everyone in this thread. I was dealing with this issue for some days. THANK YOU

**Comment by Raidus** [comment] 2017-07-07 17:01
Thanks @entrptaher for your example!

I've tried to rebuild your example, but nightmare isn't starting in my case. 

Could have a look at https://github.com/Raidus/test-electron-nightmare?

**Comment by mariodavid** [comment] 2017-07-07 19:37
@Raidus did you tried the hint from @codeofsumit? 

Adding `electronPath: require('./node_modules/electron'),` in https://github.com/Raidus/test-electron-nightmare/blob/master/night.js#L5 worked for me when i tried your example.

**Comment by Raidus** [comment] 2017-07-08 10:31
@mariodavid thanks! that solved the problem 👍

**Comment by casesandberg** [comment] 2017-08-23 19:56
Duplicate of https://github.com/segmentio/nightmare/issues/1018

**Closed by casesandberg** 2017-08-23 19:56 UTC

**Comment by carter-dewey** [comment] 2019-07-31 22:34
I have noticed that within the nightmare directory is another node modules directory with electron inside of it. So this line worked for me. This works in both development and after the application is packaged.

`electronPath: require('nightmare/node_modules/electron')`
