### ISSUE TITLE
custom headers for external page resources

### ISSUE THREAD

**Issue by stolendog** [segmentio/nightmare#920] opened 2016-12-06 14:00 UTC
if I set custom headers here:
`.goto(url, { 'mail': 'blabla@mail.com' })`
it only used for url request, but not for other page's resources like async backend api calls.
Is there any way to set headers for external resources calls ?

**Comment by rosshinkley** [comment] 2016-12-17 03:40
I think this is very, very close to #521.  Is that what you're after?

**Comment by kmacpher67** [comment] 2017-01-28 05:15
I'm trying to figure out the code snippet here, my attempts fail/ breaks from jump street. 
```window.__nightmare = {};
__nightmare.ipc = require('electron').ipcRenderer;

Nightmare.action('customHeaders', 
   //define the action to run inside Electron
   function(name, options, parent, win, details, callback) {
    //call the IPC parent's `respondTo` using the sample Action clearCache...
   // parent, win are all null options is a function, 
	parent?  webRequest.onBeforeSendHeaders(filter, (details, callback) => {
	  details.requestHeaders['auth_token'] = token
	  callback({cancel: false, requestHeaders: details.requestHeaders})
	})
   });
```
Trickery, it be either beneficial to get a sample or something a little more auto-magical , cause I'm unable to get the header to work otherwise.

**Comment by rosshinkley** [comment] 2017-02-10 04:33
Formatting appears to be a bit weird, but it looks like you're using the error-first callback for `onBeforeSendHeaders` with an error every time.   Try passing `null` as the first parameter.

It also looks like, at least at first blush, the action callback is never called, and the Nightmare-callable function is not defined.  Is there a more complete example you can supply?

**Comment by kmacpher67** [comment] 2017-02-12 11:55
Let me see what I can do without revealing my client's details. I got the function callback to work properly in basic electron main.js sample.  But still no luck on populating the request parameters so the page has them on the request. I don't think it's like this item, cause electron does the same thing. 
So I think it has to do with the http GET request on the server, even though I'm putting the (session auth creds by the way) in the header, it might be rejecting them for security reasons. IDK. 
I'm able to do that with JMETER http GET or POSTMAN, just add the auth creds to the header. 
What is different with how electron handles the session's custom request headers? 
let me see if I can create a sample and upload. thanks.  Awesome work btw.

**Comment by casesandberg** [comment] 2017-08-23 19:52
This is a duplicate of https://github.com/segmentio/nightmare/issues/521

**Closed by casesandberg** 2017-08-23 19:52 UTC
