### ISSUE TITLE
Custom actions: nightmare drag and drop function

### ISSUE THREAD

**Issue by jackSnaps** [segmentio/nightmare#1150] opened 2017-06-02 16:25 UTC
I found this code for a JS drag and drop function online (https://ghostinspector.com/blog/simulate-drag-and-drop-javascript-casperjs/) and am trying to implement it into a nightmare action. I added this code to actions.js

```
/**
 * Drag and drop an element onto another
 *
 * @param {String} selector
 * @param {Function} done
 */

 exports.dragAndDrop = function(selectorDrag, selectorDrop, done) {
  debug('.dragAndDrop ' + selectorDrag + ' on ' + selectorDrop);
  this.evaluate_now(function (selectorDrag, selectorDrop){
    // function for triggering mouse events
    var fireMouseEvent = function (type, elem, centerX, centerY) {
      var evt = document.createEvent('MouseEvents');
      evt.initMouseEvent(type, true, true, window, 1, 1, 1, centerX, centerY, false, false, false, false, 0, elem);
      elem.dispatchEvent(evt);
    };

    // fetch target elements
    var elemDrag = document.querySelector(selectorDrag);
    var elemDrop = document.querySelector(selectorDrop);
    if (!elemDrag || !elemDrop) return false;

    // calculate positions
    var pos = elemDrag.getBoundingClientRect();
    var center1X = Math.floor((pos.left + pos.right) / 2);
    var center1Y = Math.floor((pos.top + pos.bottom) / 2);
    pos = elemDrop.getBoundingClientRect();
    var center2X = Math.floor((pos.left + pos.right) / 2);
    var center2Y = Math.floor((pos.top + pos.bottom) / 2);
    
    // mouse over dragged element and mousedown
    fireMouseEvent('mousemove', elemDrag, center1X, center1Y);
    fireMouseEvent('mouseenter', elemDrag, center1X, center1Y);
    fireMouseEvent('mouseover', elemDrag, center1X, center1Y);
    fireMouseEvent('mousedown', elemDrag, center1X, center1Y);

    // start dragging process over to drop target
    fireMouseEvent('dragstart', elemDrag, center1X, center1Y);
    fireMouseEvent('drag', elemDrag, center1X, center1Y);
    fireMouseEvent('mousemove', elemDrag, center1X, center1Y);
    fireMouseEvent('drag', elemDrag, center2X, center2Y);
    fireMouseEvent('mousemove', elemDrop, center2X, center2Y);
    
    // trigger dragging process on top of drop target
    fireMouseEvent('mouseenter', elemDrop, center2X, center2Y);
    fireMouseEvent('dragenter', elemDrop, center2X, center2Y);
    fireMouseEvent('mouseover', elemDrop, center2X, center2Y);
    fireMouseEvent('dragover', elemDrop, center2X, center2Y);
    
    // release dragged element on top of drop target
    fireMouseEvent('drop', elemDrop, center2X, center2Y);
    fireMouseEvent('dragend', elemDrag, center2X, center2Y);
    fireMouseEvent('mouseup', elemDrag, center2X, center2Y);
  }, done, selectorDrag, selectorDrop);
 }; 
```

But I can't seem to get it working, nothing happens when I use it. Anyone know where I'm going wrong?

**Comment by jackSnaps** [comment] 2017-06-06 18:26
@reinpk any idea on how I could accomplish this? Thanks for the great library!

**Comment by casesandberg** [comment] 2017-08-23 19:41
Duplicate of https://github.com/segmentio/nightmare/issues/1047

**Closed by casesandberg** 2017-08-23 19:41 UTC
