### ISSUE TITLE
Search failed: Error: .wait() timed out after 30000msec

### ISSUE THREAD

**Issue by mymtw** [segmentio/nightmare#1052] opened 2017-03-19 18:27 UTC
Version:
`"nightmare": "^2.10.0",`

**Problem**:
I'm clicking button continue, after which I should be redirected, this works sometimes, but sometimes I see next error:
```
Search failed: Error: .wait() timed out after 30000msec
    at Timeout._onTimeout (/Users/apple/Developer/onetwothree/node_modules/nightmare/lib/actions.js:453:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
my code part:
```
    return nightmare
      .type('#ap_customer_name', account_name)
      .type('#ap_email', email)
      .type('#ap_password', password)
      .type('#ap_password_check', password)
      .click('#continue')
      .wait('.nav-line-1');
  })
  .then(() => {
    return nightmare
      .evaluate(() => {
        return Array
          .from(document.querySelectorAll('.nav-line-1'))
          .map(element => element.innerText);
      });
  })

```

**Comment by chtrinh** [comment] 2017-03-27 18:47
Open the electron browser and run it a couple of times like so: 
```js
nightmare({
            show: true,
            width: 1280,
            height: 800
})
```

You probably have to wait for form element to be loaded before you can actually type into the fields. 
More like than not there some lag and your nightmare execution is faster and it skips all the way to the wait action. 

or better yet just wait for each field before your type()
```
.wait('#ap_customer_name')
.type('#ap_customer_name', account_name)
```

**Comment by mymtwcom** [comment] 2017-03-27 19:00
@chtrinh I **waited already after click on submit for new element on page**

> or better yet just wait for each field before your type()

Not relevant to the issue

**Comment by rosshinkley** [comment] 2017-03-27 20:34
This smells like a captcha.  Have you used `show: true` or `.url()` to verify you're getting redirected to the same place every time?

**Comment by chtrinh** [comment] 2017-03-27 20:38
What @rosshinkley said might be the issue.

> I waited already after click on submit for new element on page
@mymtwcom: Is the form async loaded?

**Comment by mymtwcom** [comment] 2017-03-27 21:54
@rosshinkley yes, I used `show: true`. I used asserts that to know, that I'm currently on page that I need.
`CAPTCHA`: No there no was captcha, cuz I used `show: true` that to make sure.
read again plz my **problem** from issue:

I'm clicking button continue, after which I should be
 redirected, **this works sometimes, but sometimes I see** next **error**

Maybe my code will help to anybody reproduce the issue, there are used temporary proxy server also(I will disable them if issue will be reproduced), cuz I need to use them(proxy servers).

```
  "dependencies": {
    "chai": "^3.5.0",
    "nightmare": "^2.10.0",
    "randomstring": "^1.1.5"
  }
```
code: 
```
const assert = require('chai').assert,
      randomstring = require('randomstring'),
      Nightmare    = require('nightmare');

var nightmare = Nightmare({
  show: false,
  switches: {
    'proxy-server': 'socks5://52.87.57.201:9050',
    'ignore-certificate-errors': true
  }
});

const USER_AGENTS = [
  'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36',
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36',
];

const ua = USER_AGENTS[Math.floor(Math.random() * USER_AGENTS.length)];

console.log(ua);
const account_name = randomstring.generate({
  capitalization: 'lowercase',
  length: 10,
});

const email = `${randomstring.generate({
  capitalization: 'lowercase',
  length: 8
})}@gmail.com`;

const password = 'zdes23dsksfzz';

nightmare
  .useragent(ua)
  .authentication('lyft', 'Bbm7XSdP0KJi')
  .goto('https://www.amazon.com/')
  .title()
  .then((title) => {
    console.log(title);
    return nightmare
      .click('#nav-link-accountList')
      .title()
  })
  .then((title) => {
    console.log(title);
    assert.equal(title, 'Amazon Sign In')

    return nightmare
      .click('#createAccountSubmit')
      .title();
  })
  .then((title) => {
    console.log(title);
    assert.equal(title, 'Amazon Registration');

    return nightmare
      .type('#ap_customer_name', account_name)
      .type('#ap_email', email)
      .type('#ap_password', password)
      .type('#ap_password_check', password)
      .click('#continue')
      .wait('.nav-line-1');
  })
  .then(() => {
    return nightmare
      .evaluate(() => {
        return Array
          .from(document.querySelectorAll('.nav-line-1'))
          .map(element => element.innerText);
      });
  })
  .then((userGreetings) => {
    const greeting = `Hello, ${account_name}`;

    console.log(greeting);
    assert.include(userGreetings, greeting, 'array contains value');
  })
  .then(() => {
    // queue ending the Nightmare instance along with the Electron instance it wraps
    // again, return the instance to leverage the internal `.then()`
    console.log('Done');
    return nightmare.end();
  })
  .catch((error) => {
    console.error('Search failed:', error);
  });
```

**Comment by mymtwcom** [comment] 2017-03-27 21:56
@chtrinh trouble not in registration form. Trouble with waiting for new page DOM loading

**Comment by chtrinh** [comment] 2017-03-27 23:23
@mymtwcom: again... `.wait('#ap_customer_name')` sometimes yor form will load before you execute `type()`and since `type()` does raise an exception you'll just hit `.wait('.nav-line-1')` and time out. Nowhere in the code snippet are you waiting the <form> to be load on the DOM. 

So sometimes you get lucky and sometimes you don't and your test fails.. which is the behavior you are seeing.

**Comment by casesandberg** [comment] 2017-08-23 17:46
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.

**Closed by casesandberg** 2017-08-23 17:46 UTC
