### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by tinyesp** [segmentio/nightmare#1005] opened 2017-02-20 02:07 UTC
I am using nightmarejs to visit this url: 

http://www.pinbet88.com/en/

and then got this error: 

"Uncaught TypeError: Cannot read property 'stack' of null" from preload.js line 7.

**Comment by rosshinkley** [comment] 2017-02-24 03:55
This sounds like an error from the javascript on the page - the page errors get bubbled up from Electron through the preload script. 

There is an edge case, though, where I suppose the error could get emitted without an error with a stacktrace.  I _thought_ there was a PR to account for this issue,but it's entirely possible my memory is faulty.  It looks like that may be what you're hitting.  To check that's what the problem is, you could override the preload with a custom event listener on `'error'`.

**Comment by tinyesp** [comment] 2017-02-24 04:04
Thanks for the replying. I tried to override the event listener and found it is a 'Script error'. However, I do not have this exception when using Chrome or Electron. Thanks.

**Comment by casesandberg** [comment] 2017-08-22 20:54
Can you provide some more information or a code example? I am going to close this for now but feel free to re-open it with some more details.

**Closed by casesandberg** 2017-08-22 20:54 UTC
