### ISSUE TITLE
Can't run nightmare on Ubuntu 16.04

### ISSUE THREAD

**Issue by Burning-Chai** [segmentio/nightmare#1180] opened 2017-07-05 00:16 UTC
I want to run nightmare program on Ubuntu 16.04.
so I prepared sample code such as.

```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: false });

nightmare
  .viewport(1024, 768)
  .goto('https://google.com')
  .wait(1000)
  .screenshot('./hoge.png')
  .end()
  .then()
  .catch(function (error) {
     console.error('screen shot:', error);
  });
```

Also I installed some dependencies to run.

```
sudo apt-get update && sudo apt-get -y install
     make unzip g++ libssl-dev git xvfb x11-xkb-utils 
     xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic
     x11-apps clang libdbus-1-dev libgtk2.0-dev libnotify-dev
     libgnome-keyring-dev libgconf2-dev libasound2-dev
     libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev
     gcc-multilib g++-multilib
```

then, I run `DEBUG=nightmare*,electron* xvfb-run --server-args='-screen 0 1024x768x24' node --harmony index.js`

but can't run. didn't make hoge.png.

now display log such as
```
  nightmare queuing process start +0ms
  nightmare queueing action "viewport" +9ms
  nightmare queueing action "goto" for https://google.com +5ms
  nightmare queueing action "wait" +1ms
  nightmare queueing action "screenshot" +0ms
  nightmare running +2ms
  electron:stderr [11440:0705/091206.074096:FATAL:platform_font_linux.cc(63)] Check failed: typeface. Could not find any font: Nimbus Sans L, sans +495ms
  electron:stderr #0 0x000001cd013e <unknown> +2ms
  electron:stderr #1 0x000001cb53db <unknown> +0ms
  electron:stderr #2 0x000003b4c5bd <unknown> +1ms
  electron:stderr #3 0x000003b4c1ff <unknown> +0ms
  electron:stderr #4 0x000003b4ceb6 <unknown> +0ms
  electron:stderr #5 0x000003b59a79 <unknown> +0ms
  electron:stderr #6 0x000002c2825e <unknown> +0ms
  electron:stderr #7 0x000002afc6a3 <unknown> +0ms
  electron:stderr #8 0x000003c27c06 atom::api::WebContents::InitWithSessionAndOptions() +0ms
  electron:stderr #9 0x000003c28456 atom::api::WebContents::WebContents() +0ms
  electron:stderr #10 0x000003c32b96 atom::api::WebContents::Create() +1ms
  electron:stderr #11 0x000003c44395 atom::api::Window::Window() +0ms
  electron:stderr #12 0x000003c45eac atom::api::Window::New() +0ms
  electron:stderr #13 0x000003bed150 mate::internal::InvokeNew<>() +8ms
  electron:stderr #14 0x000003bed2e0 mate::internal::Dispatcher<>::DispatchToCallback() +0ms
  electron:stderr #15 0x7f5a42c80f7f <unknown> +0ms
  electron:stderr #16 0x7f5a4282b4cb <unknown> +0ms
  electron:stderr #17 0x7f5a4282af89 <unknown> +0ms
  electron:stderr #18 0x1a37fe5043a7 <unknown> +1ms
  electron:stderr  +0ms
  nightmare electron child process exited with code null: undefined +283ms
  nightmare electron child process not started yet, skipping kill. +0ms
```

If you know to solve way, please teach me.
Thank you.

```
$ node -v
v6.11.0

$ npm -v
3.10.10

"nightmare": "^2.10.0"

$ more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

$ uname -a
Linux  4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wnxhaja** [comment] 2017-07-07 02:30
We have the same setup for node npm and nightmare and it works find with me. The only difference is that I am not using `xfvb-run`. Try running it without that one. To see if the issue is in nightmare.

**Comment by JonathanBristow** [comment] 2017-07-09 12:40
Seems pretty clear - "Check failed: typeface. Could not find any font: Nimbus Sans L, sans" 
You're missing some fonts.

**Comment by casesandberg** [comment] 2017-08-23 20:17
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still a problem.

**Closed by casesandberg** 2017-08-23 20:17 UTC

**Comment by jg123** [comment] 2017-09-20 17:06
@Burning-Chai `apt install ttf-freefont`
I had the same output as you. Fix found here: https://github.com/Chatie/wechaty/issues/235#issuecomment-277627400

**Comment by Burning-Chai** [comment] 2017-09-25 05:09
@jg123 Thank you very much.
I can solve this problem. I made run correctly.

**Comment by wahengchang** [comment] 2019-01-07 10:55
@Burning-Chai  , how did you solve the problem ?

**Comment by Burning-Chai** [comment] 2019-01-08 00:20
@wahengchang I run command `apt install ttf-freefont`.
My ubuntu version is 16.04. I don't run on other versions.

**Comment by wahengchang** [comment] 2019-01-09 02:22
@Burning-Chai  thx, but it doesnt work to me. this package is not found by `apt-get`. 
I m puzzle about why is nightmare problem related to `front`?
